// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentInstance = `-- name: CreateAgentInstance :one
INSERT INTO agent_instances (room_id, template_id, worker_id, display_name, repo_path, branch_mode, model, permission_preset)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, room_id, template_id, worker_id, display_name, repo_path, branch_mode, model, permission_preset, engine_session_ref, enabled, created_at
`

type CreateAgentInstanceParams struct {
	RoomID           pgtype.UUID
	TemplateID       pgtype.UUID
	WorkerID         pgtype.UUID
	DisplayName      string
	RepoPath         string
	BranchMode       string
	Model            string
	PermissionPreset string
}

func (q *Queries) CreateAgentInstance(ctx context.Context, arg CreateAgentInstanceParams) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, createAgentInstance,
		arg.RoomID,
		arg.TemplateID,
		arg.WorkerID,
		arg.DisplayName,
		arg.RepoPath,
		arg.BranchMode,
		arg.Model,
		arg.PermissionPreset,
	)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TemplateID,
		&i.WorkerID,
		&i.DisplayName,
		&i.RepoPath,
		&i.BranchMode,
		&i.Model,
		&i.PermissionPreset,
		&i.EngineSessionRef,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createAgentTemplate = `-- name: CreateAgentTemplate :one
INSERT INTO agent_templates (name, engine, model, role_card, permission_preset, engine_options, builtin)
VALUES ($1, $2, $3, $4, $5, $6, false)
RETURNING id, name, engine, model, role_card, permission_preset, engine_options, builtin, created_at, updated_at
`

type CreateAgentTemplateParams struct {
	Name             string
	Engine           string
	Model            string
	RoleCard         string
	PermissionPreset string
	EngineOptions    []byte
}

func (q *Queries) CreateAgentTemplate(ctx context.Context, arg CreateAgentTemplateParams) (AgentTemplate, error) {
	row := q.db.QueryRow(ctx, createAgentTemplate,
		arg.Name,
		arg.Engine,
		arg.Model,
		arg.RoleCard,
		arg.PermissionPreset,
		arg.EngineOptions,
	)
	var i AgentTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Model,
		&i.RoleCard,
		&i.PermissionPreset,
		&i.EngineOptions,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureBuiltinAgentTemplate = `-- name: EnsureBuiltinAgentTemplate :exec
INSERT INTO agent_templates (name, engine, model, role_card, permission_preset, engine_options, builtin)
VALUES ($1, $2, $3, $4, $5, $6, true)
ON CONFLICT (name) DO NOTHING
`

type EnsureBuiltinAgentTemplateParams struct {
	Name             string
	Engine           string
	Model            string
	RoleCard         string
	PermissionPreset string
	EngineOptions    []byte
}

// Seeds a shipped template unless one with that name already exists, so
// user edits to builtins survive restarts.
func (q *Queries) EnsureBuiltinAgentTemplate(ctx context.Context, arg EnsureBuiltinAgentTemplateParams) error {
	_, err := q.db.Exec(ctx, ensureBuiltinAgentTemplate,
		arg.Name,
		arg.Engine,
		arg.Model,
		arg.RoleCard,
		arg.PermissionPreset,
		arg.EngineOptions,
	)
	return err
}

const getAgentInstance = `-- name: GetAgentInstance :one
SELECT id, room_id, template_id, worker_id, display_name, repo_path, branch_mode, model, permission_preset, engine_session_ref, enabled, created_at FROM agent_instances WHERE id = $1
`

func (q *Queries) GetAgentInstance(ctx context.Context, id pgtype.UUID) (AgentInstance, error) {
	row := q.db.QueryRow(ctx, getAgentInstance, id)
	var i AgentInstance
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.TemplateID,
		&i.WorkerID,
		&i.DisplayName,
		&i.RepoPath,
		&i.BranchMode,
		&i.Model,
		&i.PermissionPreset,
		&i.EngineSessionRef,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentTemplate = `-- name: GetAgentTemplate :one
SELECT id, name, engine, model, role_card, permission_preset, engine_options, builtin, created_at, updated_at FROM agent_templates WHERE id = $1
`

func (q *Queries) GetAgentTemplate(ctx context.Context, id pgtype.UUID) (AgentTemplate, error) {
	row := q.db.QueryRow(ctx, getAgentTemplate, id)
	var i AgentTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Model,
		&i.RoleCard,
		&i.PermissionPreset,
		&i.EngineOptions,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentTemplates = `-- name: ListAgentTemplates :many
SELECT id, name, engine, model, role_card, permission_preset, engine_options, builtin, created_at, updated_at FROM agent_templates ORDER BY builtin DESC, name
`

func (q *Queries) ListAgentTemplates(ctx context.Context) ([]AgentTemplate, error) {
	rows, err := q.db.Query(ctx, listAgentTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTemplate
	for rows.Next() {
		var i AgentTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engine,
			&i.Model,
			&i.RoleCard,
			&i.PermissionPreset,
			&i.EngineOptions,
			&i.Builtin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomAgentInstances = `-- name: ListRoomAgentInstances :many
SELECT id, room_id, template_id, worker_id, display_name, repo_path, branch_mode, model, permission_preset, engine_session_ref, enabled, created_at FROM agent_instances WHERE room_id = $1 ORDER BY created_at
`

func (q *Queries) ListRoomAgentInstances(ctx context.Context, roomID pgtype.UUID) ([]AgentInstance, error) {
	rows, err := q.db.Query(ctx, listRoomAgentInstances, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentInstance
	for rows.Next() {
		var i AgentInstance
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.TemplateID,
			&i.WorkerID,
			&i.DisplayName,
			&i.RepoPath,
			&i.BranchMode,
			&i.Model,
			&i.PermissionPreset,
			&i.EngineSessionRef,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentInstanceSession = `-- name: UpdateAgentInstanceSession :exec
UPDATE agent_instances SET engine_session_ref = $2 WHERE id = $1
`

type UpdateAgentInstanceSessionParams struct {
	ID               pgtype.UUID
	EngineSessionRef string
}

func (q *Queries) UpdateAgentInstanceSession(ctx context.Context, arg UpdateAgentInstanceSessionParams) error {
	_, err := q.db.Exec(ctx, updateAgentInstanceSession, arg.ID, arg.EngineSessionRef)
	return err
}

const updateAgentTemplate = `-- name: UpdateAgentTemplate :one
UPDATE agent_templates SET
    name              = $2,
    engine            = $3,
    model             = $4,
    role_card         = $5,
    permission_preset = $6,
    engine_options    = $7,
    updated_at        = now()
WHERE id = $1
RETURNING id, name, engine, model, role_card, permission_preset, engine_options, builtin, created_at, updated_at
`

type UpdateAgentTemplateParams struct {
	ID               pgtype.UUID
	Name             string
	Engine           string
	Model            string
	RoleCard         string
	PermissionPreset string
	EngineOptions    []byte
}

func (q *Queries) UpdateAgentTemplate(ctx context.Context, arg UpdateAgentTemplateParams) (AgentTemplate, error) {
	row := q.db.QueryRow(ctx, updateAgentTemplate,
		arg.ID,
		arg.Name,
		arg.Engine,
		arg.Model,
		arg.RoleCard,
		arg.PermissionPreset,
		arg.EngineOptions,
	)
	var i AgentTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engine,
		&i.Model,
		&i.RoleCard,
		&i.PermissionPreset,
		&i.EngineOptions,
		&i.Builtin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
