// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWikiMaintainer = `-- name: ClearWikiMaintainer :exec
UPDATE projects SET wiki_maintainer_member_id = NULL WHERE wiki_maintainer_member_id = $1
`

// A member taken out of its project keeps its wiki no longer.
func (q *Queries) ClearWikiMaintainer(ctx context.Context, wikiMaintainerMemberID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearWikiMaintainer, wikiMaintainerMemberID)
	return err
}

const countAgentsWithAvatar = `-- name: CountAgentsWithAvatar :one
SELECT count(*) FROM agents WHERE avatar = $1
`

// How many agents show an avatar file, asked before the file is removed.
func (q *Queries) CountAgentsWithAvatar(ctx context.Context, avatar string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentsWithAvatar, avatar)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, avatar, machine_id, runtime, model, role_card, permission_preset, runtime_options, skills)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateAgentParams struct {
	Name             string
	Avatar           string
	MachineID        pgtype.UUID
	Runtime          string
	Model            string
	RoleCard         string
	PermissionPreset string
	RuntimeOptions   []byte
	Skills           []string
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.Avatar,
		arg.MachineID,
		arg.Runtime,
		arg.Model,
		arg.RoleCard,
		arg.PermissionPreset,
		arg.RuntimeOptions,
		arg.Skills,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (room_id, agent_id, machine_id, display_name, repo_path, branch_mode, model, permission_preset, created_at)
SELECT $1, ag.id, ag.machine_id, coalesce(nullif($2::text, ''), ag.name), $3, $4, $5, $6, clock_timestamp()
FROM agents AS ag
WHERE ag.id = $7
RETURNING id, room_id, agent_id, machine_id, display_name, repo_path, branch_mode, model, permission_preset, enabled, created_at, removed_at
`

type CreateMemberParams struct {
	RoomID           pgtype.UUID
	DisplayName      string
	RepoPath         string
	BranchMode       string
	Model            string
	PermissionPreset string
	AgentID          pgtype.UUID
}

// A member runs on the machine its agent is set up on and, unless given
// one, goes by the agent's name. created_at is the clock, not the
// transaction's start: members a project starts with join together, and
// the list keeps the order they joined in even after their rows change.
func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.RoomID,
		arg.DisplayName,
		arg.RepoPath,
		arg.BranchMode,
		arg.Model,
		arg.PermissionPreset,
		arg.AgentID,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AgentID,
		&i.MachineID,
		&i.DisplayName,
		&i.RepoPath,
		&i.BranchMode,
		&i.Model,
		&i.PermissionPreset,
		&i.Enabled,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :execrows
DELETE FROM agents WHERE id = $1
`

// Members already taken out of their projects lose the link; a current
// member makes members_current_have_agent refuse the delete.
func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgent = `-- name: GetAgent :one
SELECT ag.id, ag.name, ag.avatar, ag.machine_id, ag.runtime, ag.model, ag.role_card, ag.permission_preset, ag.runtime_options, ag.skills, ag.created_at, ag.updated_at, m.name AS machine_name,
       coalesce(array_agg(DISTINCT p.name ORDER BY p.name) FILTER (WHERE p.name IS NOT NULL), '{}')::text[] AS projects
FROM agents ag
JOIN machines m ON m.id = ag.machine_id
LEFT JOIN members mb ON mb.agent_id = ag.id AND mb.removed_at IS NULL
LEFT JOIN rooms r ON r.id = mb.room_id
LEFT JOIN projects p ON p.id = r.project_id
WHERE ag.id = $1
GROUP BY ag.id, m.name
`

type GetAgentRow struct {
	Agent       Agent
	MachineName string
	Projects    []string
}

// An agent with the name of its machine and the projects it is a current
// member of.
func (q *Queries) GetAgent(ctx context.Context, id pgtype.UUID) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i GetAgentRow
	err := row.Scan(
		&i.Agent.ID,
		&i.Agent.Name,
		&i.Agent.Avatar,
		&i.Agent.MachineID,
		&i.Agent.Runtime,
		&i.Agent.Model,
		&i.Agent.RoleCard,
		&i.Agent.PermissionPreset,
		&i.Agent.RuntimeOptions,
		&i.Agent.Skills,
		&i.Agent.CreatedAt,
		&i.Agent.UpdatedAt,
		&i.MachineName,
		&i.Projects,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, room_id, agent_id, machine_id, display_name, repo_path, branch_mode, model, permission_preset, enabled, created_at, removed_at FROM members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AgentID,
		&i.MachineID,
		&i.DisplayName,
		&i.RepoPath,
		&i.BranchMode,
		&i.Model,
		&i.PermissionPreset,
		&i.Enabled,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listAgentProjects = `-- name: ListAgentProjects :many
SELECT DISTINCT p.name
FROM members mb
JOIN rooms r ON r.id = mb.room_id
JOIN projects p ON p.id = r.project_id
WHERE mb.agent_id = $1 AND mb.removed_at IS NULL
ORDER BY p.name
`

// The projects where the agent is still a current member, for telling
// someone where to take it out before deleting it.
func (q *Queries) ListAgentProjects(ctx context.Context, agentID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAgentProjects, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT ag.id, ag.name, ag.avatar, ag.machine_id, ag.runtime, ag.model, ag.role_card, ag.permission_preset, ag.runtime_options, ag.skills, ag.created_at, ag.updated_at, m.name AS machine_name,
       coalesce(array_agg(DISTINCT p.name ORDER BY p.name) FILTER (WHERE p.name IS NOT NULL), '{}')::text[] AS projects
FROM agents ag
JOIN machines m ON m.id = ag.machine_id
LEFT JOIN members mb ON mb.agent_id = ag.id AND mb.removed_at IS NULL
LEFT JOIN rooms r ON r.id = mb.room_id
LEFT JOIN projects p ON p.id = r.project_id
GROUP BY ag.id, m.name
ORDER BY ag.created_at, ag.name
`

type ListAgentsRow struct {
	Agent       Agent
	MachineName string
	Projects    []string
}

// Oldest first: the web UI's default sort is "as added", and the page
// lets you reorder by name or by last edit. Each with its machine's name
// and the projects it is a current member of.
func (q *Queries) ListAgents(ctx context.Context) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.Agent.ID,
			&i.Agent.Name,
			&i.Agent.Avatar,
			&i.Agent.MachineID,
			&i.Agent.Runtime,
			&i.Agent.Model,
			&i.Agent.RoleCard,
			&i.Agent.PermissionPreset,
			&i.Agent.RuntimeOptions,
			&i.Agent.Skills,
			&i.Agent.CreatedAt,
			&i.Agent.UpdatedAt,
			&i.MachineName,
			&i.Projects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineMembers = `-- name: ListMachineMembers :many
SELECT mb.id, mb.room_id, mb.agent_id, mb.machine_id, mb.display_name, mb.repo_path, mb.branch_mode, mb.model, mb.permission_preset, mb.enabled, mb.created_at, mb.removed_at,
       p.id AS project_id,
       p.name AS project_name,
       running.id AS turn_id,
       running.thread_id AS turn_thread_id,
       running.started_at AS turn_started_at,
       pending.id AS approval_id,
       pending.payload AS approval_payload
FROM members mb
JOIN rooms r ON r.id = mb.room_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN LATERAL (
    SELECT t.id, t.thread_id, t.started_at
    FROM turns t
    WHERE t.member_id = mb.id AND t.status = 'running'
    ORDER BY t.started_at DESC
    LIMIT 1
) running ON true
LEFT JOIN LATERAL (
    SELECT ap.id, ap.payload
    FROM approvals ap
    WHERE ap.member_id = mb.id AND ap.status = 'pending'
    ORDER BY ap.created_at
    LIMIT 1
) pending ON true
WHERE mb.machine_id = $1 AND mb.removed_at IS NULL
ORDER BY p.name, mb.created_at
`

type ListMachineMembersRow struct {
	Member          Member
	ProjectID       pgtype.UUID
	ProjectName     string
	TurnID          pgtype.UUID
	TurnThreadID    pgtype.UUID
	TurnStartedAt   pgtype.Timestamptz
	ApprovalID      pgtype.UUID
	ApprovalPayload []byte
}

// The current members a machine runs, across every project: the project
// each is in, its turn in flight if it has one, and the oldest request of
// its that waits for a person.
func (q *Queries) ListMachineMembers(ctx context.Context, machineID pgtype.UUID) ([]ListMachineMembersRow, error) {
	rows, err := q.db.Query(ctx, listMachineMembers, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachineMembersRow
	for rows.Next() {
		var i ListMachineMembersRow
		if err := rows.Scan(
			&i.Member.ID,
			&i.Member.RoomID,
			&i.Member.AgentID,
			&i.Member.MachineID,
			&i.Member.DisplayName,
			&i.Member.RepoPath,
			&i.Member.BranchMode,
			&i.Member.Model,
			&i.Member.PermissionPreset,
			&i.Member.Enabled,
			&i.Member.CreatedAt,
			&i.Member.RemovedAt,
			&i.ProjectID,
			&i.ProjectName,
			&i.TurnID,
			&i.TurnThreadID,
			&i.TurnStartedAt,
			&i.ApprovalID,
			&i.ApprovalPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT id, room_id, agent_id, machine_id, display_name, repo_path, branch_mode, model, permission_preset, enabled, created_at, removed_at FROM members WHERE room_id = $1 ORDER BY created_at
`

// Every member the room has had, including those taken out of the project:
// their messages and turns still need their names. Whoever wants only the
// current members skips the rows with removed_at set.
func (q *Queries) ListRoomMembers(ctx context.Context, roomID pgtype.UUID) ([]Member, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AgentID,
			&i.MachineID,
			&i.DisplayName,
			&i.RepoPath,
			&i.BranchMode,
			&i.Model,
			&i.PermissionPreset,
			&i.Enabled,
			&i.CreatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillAgents = `-- name: ListSkillAgents :many
SELECT id, name FROM agents WHERE $1::text = ANY(skills) ORDER BY name
`

type ListSkillAgentsRow struct {
	ID   pgtype.UUID
	Name string
}

// The agents a skill is installed for, by name.
func (q *Queries) ListSkillAgents(ctx context.Context, skill string) ([]ListSkillAgentsRow, error) {
	rows, err := q.db.Query(ctx, listSkillAgents, skill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillAgentsRow
	for rows.Next() {
		var i ListSkillAgentsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :one
UPDATE members AS mb
SET removed_at = now()
WHERE mb.id = $1
  AND mb.removed_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM turns AS t WHERE t.member_id = mb.id AND t.status = 'running')
RETURNING id, room_id, agent_id, machine_id, display_name, repo_path, branch_mode, model, permission_preset, enabled, created_at, removed_at
`

// Takes a member out of its project unless one of its turns is still
// running. The row stays for the history that points at it.
func (q *Queries) RemoveMember(ctx context.Context, id pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, removeMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AgentID,
		&i.MachineID,
		&i.DisplayName,
		&i.RepoPath,
		&i.BranchMode,
		&i.Model,
		&i.PermissionPreset,
		&i.Enabled,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const setAgentSkill = `-- name: SetAgentSkill :execrows
UPDATE agents SET
    skills = CASE
        WHEN NOT $1::boolean THEN array_remove(skills, $2::text)
        WHEN $2::text = ANY(skills) THEN skills
        ELSE array_append(skills, $2::text)
    END,
    updated_at = now()
WHERE id = $3
`

type SetAgentSkillParams struct {
	Installed bool
	Skill     string
	ID        pgtype.UUID
}

// Installs a skill for an agent, once, or takes it off.
func (q *Queries) SetAgentSkill(ctx context.Context, arg SetAgentSkillParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAgentSkill, arg.Installed, arg.Skill, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents AS ag SET
    name              = $1,
    avatar            = $2,
    machine_id        = $3,
    runtime           = $4,
    model             = $5,
    role_card         = $6,
    permission_preset = $7,
    runtime_options   = $8,
    skills            = $9::text[],
    updated_at        = now()
WHERE ag.id = $10
  AND (ag.machine_id = $3
       OR NOT EXISTS (SELECT 1 FROM members AS mb WHERE mb.agent_id = ag.id AND mb.removed_at IS NULL))
RETURNING ag.id
`

type UpdateAgentParams struct {
	Name             string
	Avatar           string
	MachineID        pgtype.UUID
	Runtime          string
	Model            string
	RoleCard         string
	PermissionPreset string
	RuntimeOptions   []byte
	Skills           []string
	ID               pgtype.UUID
}

// Replaces every editable field. The machine changes only while the agent
// is a member of no project, since its members run there; no row back is
// an unknown agent or a move refused.
func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Avatar,
		arg.MachineID,
		arg.Runtime,
		arg.Model,
		arg.RoleCard,
		arg.PermissionPreset,
		arg.RuntimeOptions,
		arg.Skills,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET display_name      = coalesce($2, display_name),
    model             = coalesce($3, model),
    permission_preset = coalesce($4, permission_preset),
    repo_path         = coalesce($5, repo_path),
    enabled           = coalesce($6, enabled)
WHERE id = $1 AND removed_at IS NULL
RETURNING id, room_id, agent_id, machine_id, display_name, repo_path, branch_mode, model, permission_preset, enabled, created_at, removed_at
`

type UpdateMemberParams struct {
	ID               pgtype.UUID
	DisplayName      pgtype.Text
	Model            pgtype.Text
	PermissionPreset pgtype.Text
	RepoPath         pgtype.Text
	Enabled          pgtype.Bool
}

// Changes the fields a person may edit after adding a member; a NULL
// argument keeps the current value. A member taken out of its project is
// not edited any more.
func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.DisplayName,
		arg.Model,
		arg.PermissionPreset,
		arg.RepoPath,
		arg.Enabled,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AgentID,
		&i.MachineID,
		&i.DisplayName,
		&i.RepoPath,
		&i.BranchMode,
		&i.Model,
		&i.PermissionPreset,
		&i.Enabled,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}
