// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, message_id)
VALUES (COALESCE($9::uuid, gen_random_uuid()), $1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, status, message, message_id, decided_by, created_at, decided_at
`

type CreateApprovalParams struct {
	TurnID    pgtype.UUID
	RoomID    pgtype.UUID
	ThreadID  pgtype.UUID
	MemberID  pgtype.UUID
	RequestID string
	Kind      string
	Payload   []byte
	MessageID pgtype.UUID
	ID        pgtype.UUID
}

// The caller may supply the id so it can announce the approval before the
// row exists; a null id lets the database assign one.
func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.TurnID,
		arg.RoomID,
		arg.ThreadID,
		arg.MemberID,
		arg.RequestID,
		arg.Kind,
		arg.Payload,
		arg.MessageID,
		arg.ID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.RequestID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Message,
		&i.MessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals SET
    status     = $2,
    message    = $3,
    decided_by = $4,
    decided_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, status, message, message_id, decided_by, created_at, decided_at
`

type DecideApprovalParams struct {
	ID        pgtype.UUID
	Status    string
	Message   string
	DecidedBy pgtype.UUID
}

// The first decision wins: only a pending approval can be decided, so two
// people answering at once cannot both succeed.
func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApproval,
		arg.ID,
		arg.Status,
		arg.Message,
		arg.DecidedBy,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.RequestID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Message,
		&i.MessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, status, message, message_id, decided_by, created_at, decided_at FROM approvals WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id pgtype.UUID) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.TurnID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.RequestID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Message,
		&i.MessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT ap.id, ap.turn_id, ap.room_id, ap.thread_id, ap.member_id, ap.request_id, ap.kind, ap.payload, ap.status, ap.message, ap.message_id, ap.decided_by, ap.created_at, ap.decided_at, mb.display_name AS member_name, p.name AS project_name
FROM approvals ap
JOIN members mb ON mb.id = ap.member_id
JOIN rooms r ON r.id = ap.room_id
JOIN projects p ON p.id = r.project_id
WHERE ap.status = 'pending'
ORDER BY ap.created_at
`

type ListPendingApprovalsRow struct {
	Approval    Approval
	MemberName  string
	ProjectName string
}

// Every request waiting for a person, across every room, oldest first,
// with the names the "for me" page shows so it needs no second lookup.
func (q *Queries) ListPendingApprovals(ctx context.Context) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalsRow
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(
			&i.Approval.ID,
			&i.Approval.TurnID,
			&i.Approval.RoomID,
			&i.Approval.ThreadID,
			&i.Approval.MemberID,
			&i.Approval.RequestID,
			&i.Approval.Kind,
			&i.Approval.Payload,
			&i.Approval.Status,
			&i.Approval.Message,
			&i.Approval.MessageID,
			&i.Approval.DecidedBy,
			&i.Approval.CreatedAt,
			&i.Approval.DecidedAt,
			&i.MemberName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRoomApprovals = `-- name: ListPendingRoomApprovals :many
SELECT id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, status, message, message_id, decided_by, created_at, decided_at FROM approvals WHERE room_id = $1 AND status = 'pending' ORDER BY created_at
`

// Oldest first: the order people should deal with them in.
func (q *Queries) ListPendingRoomApprovals(ctx context.Context, roomID pgtype.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingRoomApprovals, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.RoomID,
			&i.ThreadID,
			&i.MemberID,
			&i.RequestID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Message,
			&i.MessageID,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnApprovals = `-- name: ListTurnApprovals :many
SELECT id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, status, message, message_id, decided_by, created_at, decided_at FROM approvals WHERE turn_id = $1 ORDER BY created_at
`

func (q *Queries) ListTurnApprovals(ctx context.Context, turnID pgtype.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listTurnApprovals, turnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.RoomID,
			&i.ThreadID,
			&i.MemberID,
			&i.RequestID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Message,
			&i.MessageID,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTurnApprovals = `-- name: ResolveTurnApprovals :many
UPDATE approvals SET
    status     = $2,
    message    = $3,
    decided_at = now()
WHERE turn_id = $1 AND status = 'pending'
RETURNING id, turn_id, room_id, thread_id, member_id, request_id, kind, payload, status, message, message_id, decided_by, created_at, decided_at
`

type ResolveTurnApprovalsParams struct {
	TurnID  pgtype.UUID
	Status  string
	Message string
}

// Closes every pending approval of a turn, for when the turn ends before
// anyone decided.
func (q *Queries) ResolveTurnApprovals(ctx context.Context, arg ResolveTurnApprovalsParams) ([]Approval, error) {
	rows, err := q.db.Query(ctx, resolveTurnApprovals, arg.TurnID, arg.Status, arg.Message)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Approval
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.TurnID,
			&i.RoomID,
			&i.ThreadID,
			&i.MemberID,
			&i.RequestID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Message,
			&i.MessageID,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
