// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAttachments = `-- name: ClaimAttachments :many
UPDATE attachments SET message_id = $1
WHERE id = ANY($2::uuid[]) AND room_id = $3 AND message_id IS NULL
RETURNING id, room_id, message_id, filename, media_type, size, path, created_at
`

type ClaimAttachmentsParams struct {
	MessageID pgtype.UUID
	Ids       []pgtype.UUID
	RoomID    pgtype.UUID
}

// Ties uploads to the message that carries them. Only unclaimed uploads
// of the same room qualify, so an id from elsewhere is simply not returned.
func (q *Queries) ClaimAttachments(ctx context.Context, arg ClaimAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, claimAttachments, arg.MessageID, arg.Ids, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MessageID,
			&i.Filename,
			&i.MediaType,
			&i.Size,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, room_id, filename, media_type, size, path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, room_id, message_id, filename, media_type, size, path, created_at
`

type CreateAttachmentParams struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Filename  string
	MediaType string
	Size      int64
	Path      string
}

// The id comes from the caller: the file is named after it on disk before
// the row exists.
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.RoomID,
		arg.Filename,
		arg.MediaType,
		arg.Size,
		arg.Path,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.MessageID,
		&i.Filename,
		&i.MediaType,
		&i.Size,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, room_id, message_id, filename, media_type, size, path, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.MessageID,
		&i.Filename,
		&i.MediaType,
		&i.Size,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByMessages = `-- name: ListAttachmentsByMessages :many
SELECT id, room_id, message_id, filename, media_type, size, path, created_at FROM attachments
WHERE message_id = ANY($1::uuid[])
ORDER BY created_at, id
`

func (q *Queries) ListAttachmentsByMessages(ctx context.Context, messageIds []pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByMessages, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MessageID,
			&i.Filename,
			&i.MediaType,
			&i.Size,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
