// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brief.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRoomNews = `-- name: ListRoomNews :many
SELECT m.id, m.seq, m.room_id, m.thread_id, m.sender_kind, m.user_id, m.member_id, m.body, m.mentions, m.created_at, m.turn_id, m.title,
       coalesce(t.number, 0)::int AS topic_number,
       count(*) OVER () AS total
FROM messages m
LEFT JOIN threads t ON t.root_message_id = m.id
LEFT JOIN turns tu ON tu.id = m.turn_id
WHERE m.room_id = $1
  AND m.thread_id IS NULL
  AND m.seq > $2::bigint AND m.seq <= $3::bigint
  AND ($4::uuid IS NULL OR tu.session_id IS DISTINCT FROM $4::uuid)
ORDER BY m.seq DESC
LIMIT $5
`

type ListRoomNewsParams struct {
	RoomID    pgtype.UUID
	After     int64
	UpTo      int64
	SessionID pgtype.UUID
	MaxRows   int32
}

type ListRoomNewsRow struct {
	Message     Message
	TopicNumber int32
	Total       int64
}

// Top-level messages of a room in (after, up_to], the newest `limit` of
// them, newest first, each with the number of the topic it heads (0 when
// none) and the count of all that matched.
func (q *Queries) ListRoomNews(ctx context.Context, arg ListRoomNewsParams) ([]ListRoomNewsRow, error) {
	rows, err := q.db.Query(ctx, listRoomNews,
		arg.RoomID,
		arg.After,
		arg.UpTo,
		arg.SessionID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomNewsRow
	for rows.Next() {
		var i ListRoomNewsRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.Seq,
			&i.Message.RoomID,
			&i.Message.ThreadID,
			&i.Message.SenderKind,
			&i.Message.UserID,
			&i.Message.MemberID,
			&i.Message.Body,
			&i.Message.Mentions,
			&i.Message.CreatedAt,
			&i.Message.TurnID,
			&i.Message.Title,
			&i.TopicNumber,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadNews = `-- name: ListThreadNews :many
SELECT m.id, m.seq, m.room_id, m.thread_id, m.sender_kind, m.user_id, m.member_id, m.body, m.mentions, m.created_at, m.turn_id, m.title, count(*) OVER () AS total
FROM messages m
LEFT JOIN turns tu ON tu.id = m.turn_id
WHERE m.thread_id = $1
  AND m.seq > $2::bigint AND m.seq <= $3::bigint
  AND ($4::uuid IS NULL OR tu.session_id IS DISTINCT FROM $4::uuid)
ORDER BY m.seq DESC
LIMIT $5
`

type ListThreadNewsParams struct {
	ThreadID  pgtype.UUID
	After     int64
	UpTo      int64
	SessionID pgtype.UUID
	MaxRows   int32
}

type ListThreadNewsRow struct {
	Message Message
	Total   int64
}

// Replies of a thread in (after, up_to], the newest `limit` of them,
// newest first, with the count of all that matched. With after 0 and no
// session it is the tail of the whole thread.
func (q *Queries) ListThreadNews(ctx context.Context, arg ListThreadNewsParams) ([]ListThreadNewsRow, error) {
	rows, err := q.db.Query(ctx, listThreadNews,
		arg.ThreadID,
		arg.After,
		arg.UpTo,
		arg.SessionID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadNewsRow
	for rows.Next() {
		var i ListThreadNewsRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.Seq,
			&i.Message.RoomID,
			&i.Message.ThreadID,
			&i.Message.SenderKind,
			&i.Message.UserID,
			&i.Message.MemberID,
			&i.Message.Body,
			&i.Message.Mentions,
			&i.Message.CreatedAt,
			&i.Message.TurnID,
			&i.Message.Title,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicNews = `-- name: ListTopicNews :many
SELECT n.thread_id, n.number, n.new_count, n.total, r.id, r.seq, r.room_id, r.thread_id, r.sender_kind, r.user_id, r.member_id, r.body, r.mentions, r.created_at, r.turn_id, r.title, l.id, l.seq, l.room_id, l.thread_id, l.sender_kind, l.user_id, l.member_id, l.body, l.mentions, l.created_at, l.turn_id, l.title
FROM (
    SELECT t.id AS thread_id, t.number, t.root_message_id,
           count(*) AS new_count,
           max(m.seq)::bigint AS last_seq,
           count(*) OVER () AS total
    FROM messages m
    JOIN threads t ON t.id = m.thread_id
    LEFT JOIN turns tu ON tu.id = m.turn_id
    WHERE m.room_id = $1
      AND m.seq > $2::bigint AND m.seq <= $3::bigint
      AND t.id <> $4::uuid
      AND ($5::uuid IS NULL OR tu.session_id IS DISTINCT FROM $5::uuid)
    GROUP BY t.id, t.number, t.root_message_id
    ORDER BY last_seq DESC
    LIMIT $6
) n
JOIN messages r ON r.id = n.root_message_id
JOIN messages l ON l.seq = n.last_seq
ORDER BY n.last_seq DESC
`

type ListTopicNewsParams struct {
	RoomID         pgtype.UUID
	After          int64
	UpTo           int64
	ExceptThreadID pgtype.UUID
	SessionID      pgtype.UUID
	MaxRows        int32
}

type ListTopicNewsRow struct {
	ThreadID  pgtype.UUID
	Number    int32
	NewCount  int64
	Total     int64
	Message   Message
	Message_2 Message
}

// Topics of a room with replies in (after, up_to], other than one, most
// recently active first: how many replies, the root and the last of them,
// and the count of all topics that matched.
func (q *Queries) ListTopicNews(ctx context.Context, arg ListTopicNewsParams) ([]ListTopicNewsRow, error) {
	rows, err := q.db.Query(ctx, listTopicNews,
		arg.RoomID,
		arg.After,
		arg.UpTo,
		arg.ExceptThreadID,
		arg.SessionID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopicNewsRow
	for rows.Next() {
		var i ListTopicNewsRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Number,
			&i.NewCount,
			&i.Total,
			&i.Message.ID,
			&i.Message.Seq,
			&i.Message.RoomID,
			&i.Message.ThreadID,
			&i.Message.SenderKind,
			&i.Message.UserID,
			&i.Message.MemberID,
			&i.Message.Body,
			&i.Message.Mentions,
			&i.Message.CreatedAt,
			&i.Message.TurnID,
			&i.Message.Title,
			&i.Message_2.ID,
			&i.Message_2.Seq,
			&i.Message_2.RoomID,
			&i.Message_2.ThreadID,
			&i.Message_2.SenderKind,
			&i.Message_2.UserID,
			&i.Message_2.MemberID,
			&i.Message_2.Body,
			&i.Message_2.Mentions,
			&i.Message_2.CreatedAt,
			&i.Message_2.TurnID,
			&i.Message_2.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomPosition = `-- name: RoomPosition :one

SELECT coalesce(max(seq), 0)::bigint AS position FROM messages WHERE room_id = $1
`

// What a brief is put together from: what a session has not read yet. Every
// query is bounded above by the position the brief is taken at, so the
// parts of one brief agree on what "now" is, and leaves out what the
// session said itself (messages of turns that ran in it), which it
// remembers without being told.
// The seq of the room's newest message: where the room stands now.
func (q *Queries) RoomPosition(ctx context.Context, roomID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, roomPosition, roomID)
	var position int64
	err := row.Scan(&position)
	return position, err
}
