// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTurnWikiLookups = `-- name: ListTurnWikiLookups :many
SELECT id, project_id, turn_id, scope, query, hits, path, created_at FROM wiki_lookups WHERE turn_id = ANY($1::uuid[]) ORDER BY id
`

// The lookups of the turns given, in the order they were made.
func (q *Queries) ListTurnWikiLookups(ctx context.Context, turnIds []pgtype.UUID) ([]WikiLookup, error) {
	rows, err := q.db.Query(ctx, listTurnWikiLookups, turnIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WikiLookup
	for rows.Next() {
		var i WikiLookup
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TurnID,
			&i.Scope,
			&i.Query,
			&i.Hits,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWikiLookups = `-- name: PruneWikiLookups :execrows
DELETE FROM wiki_lookups WHERE created_at < $1
`

// Drops the lookups older than a time, of every project.
func (q *Queries) PruneWikiLookups(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWikiLookups, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWikiLookup = `-- name: RecordWikiLookup :exec
INSERT INTO wiki_lookups (project_id, turn_id, scope, query, hits, path)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordWikiLookupParams struct {
	ProjectID pgtype.UUID
	TurnID    pgtype.UUID
	Scope     string
	Query     string
	Hits      int32
	Path      string
}

// Records one search or read of a chat turn in a wiki (design.md 5.23.7).
func (q *Queries) RecordWikiLookup(ctx context.Context, arg RecordWikiLookupParams) error {
	_, err := q.db.Exec(ctx, recordWikiLookup,
		arg.ProjectID,
		arg.TurnID,
		arg.Scope,
		arg.Query,
		arg.Hits,
		arg.Path,
	)
	return err
}

const wikiLookedUpSince = `-- name: WikiLookedUpSince :many
SELECT DISTINCT path FROM wiki_lookups
WHERE project_id = $1 AND scope = 'project' AND created_at >= $2
`

type WikiLookedUpSinceParams struct {
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// What the project's wiki was looked up for since a time: every page read,
// and an empty path when there was any search.
func (q *Queries) WikiLookedUpSince(ctx context.Context, arg WikiLookedUpSinceParams) ([]string, error) {
	rows, err := q.db.Query(ctx, wikiLookedUpSince, arg.ProjectID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wikiLookupsBefore = `-- name: WikiLookupsBefore :one
SELECT EXISTS (SELECT 1 FROM wiki_lookups WHERE project_id = $1 AND created_at < $2)
`

type WikiLookupsBeforeParams struct {
	ProjectID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// Whether the project kept any lookups from before a time.
func (q *Queries) WikiLookupsBefore(ctx context.Context, arg WikiLookupsBeforeParams) (bool, error) {
	row := q.db.QueryRow(ctx, wikiLookupsBefore, arg.ProjectID, arg.CreatedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
