// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: machines.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (name, runtimes)
VALUES ($1, $2)
RETURNING id, name, runtimes, connected_at, last_seen_at, disconnected_at
`

type CreateMachineParams struct {
	Name     string
	Runtimes []byte
}

// Registers a machine the hub has not seen before.
func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, createMachine, arg.Name, arg.Runtimes)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtimes,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const getMachine = `-- name: GetMachine :one
SELECT id, name, runtimes, connected_at, last_seen_at, disconnected_at FROM machines WHERE id = $1
`

func (q *Queries) GetMachine(ctx context.Context, id pgtype.UUID) (Machine, error) {
	row := q.db.QueryRow(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtimes,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, name, runtimes, connected_at, last_seen_at, disconnected_at FROM machines ORDER BY name, connected_at
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.Query(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Runtimes,
			&i.ConnectedAt,
			&i.LastSeenAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMachineDisconnected = `-- name: MarkMachineDisconnected :exec
UPDATE machines SET disconnected_at = now() WHERE id = $1
`

func (q *Queries) MarkMachineDisconnected(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMachineDisconnected, id)
	return err
}

const reconnectMachine = `-- name: ReconnectMachine :one
UPDATE machines SET
    name            = $2,
    runtimes         = $3,
    connected_at    = now(),
    last_seen_at    = now(),
    disconnected_at = NULL
WHERE id = $1
RETURNING id, name, runtimes, connected_at, last_seen_at, disconnected_at
`

type ReconnectMachineParams struct {
	ID       pgtype.UUID
	Name     string
	Runtimes []byte
}

// Re-registers a known machine: refreshes its label and runtimes and resets
// the connection timestamps. Yields no row when the id is unknown.
func (q *Queries) ReconnectMachine(ctx context.Context, arg ReconnectMachineParams) (Machine, error) {
	row := q.db.QueryRow(ctx, reconnectMachine, arg.ID, arg.Name, arg.Runtimes)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Runtimes,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const touchMachine = `-- name: TouchMachine :exec
UPDATE machines SET last_seen_at = now() WHERE id = $1
`

// Records that the machine was heard from.
func (q *Queries) TouchMachine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchMachine, id)
	return err
}

const updateMachineRuntimes = `-- name: UpdateMachineRuntimes :exec
UPDATE machines SET runtimes = $2, last_seen_at = now() WHERE id = $1
`

type UpdateMachineRuntimesParams struct {
	ID       pgtype.UUID
	Runtimes []byte
}

func (q *Queries) UpdateMachineRuntimes(ctx context.Context, arg UpdateMachineRuntimesParams) error {
	_, err := q.db.Exec(ctx, updateMachineRuntimes, arg.ID, arg.Runtimes)
	return err
}
