// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const chainWork = `-- name: ChainWork :one
WITH c AS (
    SELECT id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at FROM turns WHERE chain_message_id = $1
), origin AS (
    SELECT thread_id FROM c ORDER BY started_at LIMIT 1
)
SELECT (SELECT thread_id FROM origin)::uuid AS thread_id,
       coalesce((SELECT th.number FROM threads th WHERE th.id = (SELECT thread_id FROM origin)), 0)::int AS thread_number,
       (SELECT count(*) FROM c)::int AS turns,
       (SELECT min(started_at) FROM c)::timestamptz AS started_at,
       (SELECT CASE WHEN bool_or(ended_at IS NULL) THEN NULL ELSE max(ended_at) END FROM c)::timestamptz AS ended_at,
       coalesce((SELECT bool_or(status = 'running') FROM c), false)::bool AS running,
       coalesce((SELECT status FROM c ORDER BY ended_at DESC NULLS FIRST, started_at DESC LIMIT 1), '')::text AS last_status,
       coalesce((SELECT array_agg(x.member_id ORDER BY x.first) FROM (
           SELECT member_id, min(started_at) AS first FROM c GROUP BY member_id
       ) x), '{}')::uuid[] AS members
`

type ChainWorkRow struct {
	ThreadID     pgtype.UUID
	ThreadNumber int32
	Turns        int32
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	Running      bool
	LastStatus   string
	Members      []pgtype.UUID
}

// A piece of work across its topics: the topic it began in, how many turns
// it took, when it began and, once none runs, when it ended, how it stands
// by its latest turn (running while one runs, else how the turn that ended
// last ended), and the members who took turns in it, in the order they
// first did.
func (q *Queries) ChainWork(ctx context.Context, chainMessageID pgtype.UUID) (ChainWorkRow, error) {
	row := q.db.QueryRow(ctx, chainWork, chainMessageID)
	var i ChainWorkRow
	err := row.Scan(
		&i.ThreadID,
		&i.ThreadNumber,
		&i.Turns,
		&i.StartedAt,
		&i.EndedAt,
		&i.Running,
		&i.LastStatus,
		&i.Members,
	)
	return i, err
}

const countUnreadMentions = `-- name: CountUnreadMentions :one
SELECT count(*) FROM messages m
WHERE m.mentions @> $1::jsonb
  AND NOT EXISTS (SELECT 1 FROM inbox_reads ir WHERE ir.user_id = $2 AND ir.message_id = m.id)
`

type CountUnreadMentionsParams struct {
	Needle []byte
	UserID pgtype.UUID
}

// How many of the messages that mention one user they have not read.
func (q *Queries) CountUnreadMentions(ctx context.Context, arg CountUnreadMentionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadMentions, arg.Needle, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, thread_id, sender_kind, user_id, member_id, body, mentions, turn_id, title)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title
`

type CreateMessageParams struct {
	RoomID     pgtype.UUID
	ThreadID   pgtype.UUID
	SenderKind string
	UserID     pgtype.UUID
	MemberID   pgtype.UUID
	Body       string
	Mentions   []byte
	TurnID     pgtype.UUID
	Title      string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.RoomID,
		arg.ThreadID,
		arg.SenderKind,
		arg.UserID,
		arg.MemberID,
		arg.Body,
		arg.Mentions,
		arg.TurnID,
		arg.Title,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.MemberID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
		&i.TurnID,
		&i.Title,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.MemberID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
		&i.TurnID,
		&i.Title,
	)
	return i, err
}

const lastAgentMessageInThread = `-- name: LastAgentMessageInThread :one
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title FROM messages
WHERE sender_kind = 'agent'
  AND (thread_id = $1 OR id = (SELECT root_message_id FROM threads WHERE id = $1))
ORDER BY seq DESC
LIMIT 1
`

// The most recent agent message in a topic, counting the root; used to
// pick who answers a message that mentions nobody.
func (q *Queries) LastAgentMessageInThread(ctx context.Context, threadID pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, lastAgentMessageInThread, threadID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.MemberID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
		&i.TurnID,
		&i.Title,
	)
	return i, err
}

const listRoomMessagesAfter = `-- name: ListRoomMessagesAfter :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title FROM messages
WHERE room_id = $1 AND thread_id IS NULL AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListRoomMessagesAfterParams struct {
	RoomID pgtype.UUID
	Seq    int64
	Limit  int32
}

// Top-level messages of a room newer than a cursor, oldest first.
func (q *Queries) ListRoomMessagesAfter(ctx context.Context, arg ListRoomMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRoomMessagesAfter, arg.RoomID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.MemberID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
			&i.TurnID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMessagesBefore = `-- name: ListRoomMessagesBefore :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title FROM messages
WHERE room_id = $1 AND thread_id IS NULL AND seq < $2
ORDER BY seq DESC
LIMIT $3
`

type ListRoomMessagesBeforeParams struct {
	RoomID pgtype.UUID
	Seq    int64
	Limit  int32
}

// Top-level messages of a room older than a cursor, newest first; callers
// reverse the page to present it chronologically.
func (q *Queries) ListRoomMessagesBefore(ctx context.Context, arg ListRoomMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRoomMessagesBefore, arg.RoomID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.MemberID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
			&i.TurnID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessagesAfter = `-- name: ListThreadMessagesAfter :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title FROM messages
WHERE thread_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListThreadMessagesAfterParams struct {
	ThreadID pgtype.UUID
	Seq      int64
	Limit    int32
}

// Replies in a thread newer than a cursor, oldest first. The root message
// is not a reply and is fetched separately.
func (q *Queries) ListThreadMessagesAfter(ctx context.Context, arg ListThreadMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listThreadMessagesAfter, arg.ThreadID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.MemberID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
			&i.TurnID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessagesBefore = `-- name: ListThreadMessagesBefore :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title FROM messages
WHERE thread_id = $1 AND seq < $2
ORDER BY seq DESC
LIMIT $3
`

type ListThreadMessagesBeforeParams struct {
	ThreadID pgtype.UUID
	Seq      int64
	Limit    int32
}

// The most recent replies in a thread, newest first; callers reverse the
// page to present it chronologically.
func (q *Queries) ListThreadMessagesBefore(ctx context.Context, arg ListThreadMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listThreadMessagesBefore, arg.ThreadID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.MemberID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
			&i.TurnID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMentions = `-- name: ListUserMentions :many
SELECT m.id, m.seq, m.room_id, m.thread_id, m.sender_kind, m.user_id, m.member_id, m.body, m.mentions, m.created_at, m.turn_id, m.title, r.name AS room_name, p.name AS project_name, coalesce(u.name, mb.display_name, '')::text AS sender_name,
       (ir.message_id IS NOT NULL)::boolean AS read
FROM messages m
JOIN rooms r ON r.id = m.room_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN members mb ON mb.id = m.member_id
LEFT JOIN inbox_reads ir ON ir.message_id = m.id AND ir.user_id = $1
WHERE m.mentions @> $2::jsonb AND m.seq < $3
ORDER BY m.seq DESC
LIMIT $4
`

type ListUserMentionsParams struct {
	UserID pgtype.UUID
	Needle []byte
	Before int64
	Max    int32
}

type ListUserMentionsRow struct {
	ID          pgtype.UUID
	Seq         int64
	RoomID      pgtype.UUID
	ThreadID    pgtype.UUID
	SenderKind  string
	UserID      pgtype.UUID
	MemberID    pgtype.UUID
	Body        string
	Mentions    []byte
	CreatedAt   pgtype.Timestamptz
	TurnID      pgtype.UUID
	Title       string
	RoomName    string
	ProjectName string
	SenderName  string
	Read        bool
}

// Messages that mention one user, newest first, with the names the inbox
// shows so it needs no second lookup, and whether the user read them.
func (q *Queries) ListUserMentions(ctx context.Context, arg ListUserMentionsParams) ([]ListUserMentionsRow, error) {
	rows, err := q.db.Query(ctx, listUserMentions,
		arg.UserID,
		arg.Needle,
		arg.Before,
		arg.Max,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMentionsRow
	for rows.Next() {
		var i ListUserMentionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.MemberID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
			&i.TurnID,
			&i.Title,
			&i.RoomName,
			&i.ProjectName,
			&i.SenderName,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMentionsRead = `-- name: MarkMentionsRead :execrows
INSERT INTO inbox_reads (user_id, message_id)
SELECT $1, m.id FROM messages m
WHERE m.mentions @> $2::jsonb
  AND (m.id = ANY ($3::uuid[])
       OR m.thread_id = $4
       OR m.id = (SELECT t.root_message_id FROM threads t WHERE t.id = $4)
       OR m.seq <= $5)
ON CONFLICT DO NOTHING
`

type MarkMentionsReadParams struct {
	UserID   pgtype.UUID
	Needle   []byte
	Ids      []pgtype.UUID
	ThreadID pgtype.UUID
	UpTo     int64
}

// Marks read, of the messages that mention one user, those named, those in
// a topic (its root and replies), or all up to a seq; zero or empty picks
// none by that way. How many were not read before.
func (q *Queries) MarkMentionsRead(ctx context.Context, arg MarkMentionsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMentionsRead,
		arg.UserID,
		arg.Needle,
		arg.Ids,
		arg.ThreadID,
		arg.UpTo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMessageTitle = `-- name: SetMessageTitle :one
UPDATE messages SET title = $2
WHERE id = $1
RETURNING id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title
`

type SetMessageTitleParams struct {
	ID    pgtype.UUID
	Title string
}

// Names the task a message hands on: a topic root an agent filled in with
// what it sent (design.md 5.24).
func (q *Queries) SetMessageTitle(ctx context.Context, arg SetMessageTitleParams) (Message, error) {
	row := q.db.QueryRow(ctx, setMessageTitle, arg.ID, arg.Title)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.MemberID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
		&i.TurnID,
		&i.Title,
	)
	return i, err
}

const talkingMemberInThread = `-- name: TalkingMemberInThread :many
WITH topic AS (
    SELECT th.root_message_id FROM threads th WHERE th.id = $1
), exchanges AS (
    SELECT m.member_id::text AS member_id, m.created_at AS at FROM messages m
    WHERE m.sender_kind = 'agent'
      AND (m.thread_id = $1 OR m.id = (SELECT root_message_id FROM topic))
      AND m.mentions @> jsonb_build_array(jsonb_build_object('kind', 'user', 'id', $2::uuid::text))
    UNION ALL
    SELECT x.mention->>'id', m.created_at FROM messages m, jsonb_array_elements(m.mentions) AS x(mention)
    WHERE m.sender_kind = 'user' AND m.user_id = $2::uuid
      AND (m.thread_id = $1 OR m.id = (SELECT root_message_id FROM topic))
      AND x.mention->>'kind' = 'agent'
    UNION ALL
    SELECT t.member_id::text, q.created_at FROM turns t
    JOIN messages q ON q.id = t.trigger_message_id
    WHERE t.thread_id = $1 AND q.sender_kind = 'user' AND q.user_id = $2::uuid
)
SELECT DISTINCT e.member_id::text FROM exchanges e
WHERE e.at = (SELECT max(at) FROM exchanges)
`

type TalkingMemberInThreadParams struct {
	ThreadID pgtype.UUID
	UserID   pgtype.UUID
}

// The members in a person's latest exchange in a topic (design.md 4.2),
// the root counted as the topic's: a member's message that mentions them;
// a message of theirs that names a member, whose wake may still wait in a
// queue; a turn a message of theirs set going (a reply given in one go,
// heading its topic, mentions no one). One member is the one they talk
// with; several, one message having asked them all, are none of them.
func (q *Queries) TalkingMemberInThread(ctx context.Context, arg TalkingMemberInThreadParams) ([]string, error) {
	rows, err := q.db.Query(ctx, talkingMemberInThread, arg.ThreadID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var e_member_id string
		if err := rows.Scan(&e_member_id); err != nil {
			return nil, err
		}
		items = append(items, e_member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const threadSummaries = `-- name: ThreadSummaries :many
SELECT t.root_message_id,
       t.id AS thread_id,
       t.number AS thread_number,
       (SELECT count(*) FROM messages m WHERE m.thread_id = t.id) AS reply_count,
       (SELECT max(m.created_at) FROM messages m WHERE m.thread_id = t.id)::timestamptz AS last_reply_at,
       (SELECT count(*) FROM turns tu WHERE tu.thread_id = t.id) AS turn_count,
       coalesce(lt.id::text, '')::text AS last_turn_id,
       coalesce(lt.member_id::text, '')::text AS last_turn_member_id,
       coalesce(lt.status, '') AS last_turn_status,
       coalesce(lt.error, '') AS last_turn_error,
       lt.started_at AS last_turn_started_at,
       lt.ended_at AS last_turn_ended_at,
       coalesce(w.chain::text, '')::text AS work_chain,
       coalesce(w.turns, 0)::int AS work_turns,
       w.started_at::timestamptz AS work_started_at,
       w.ended_at::timestamptz AS work_ended_at,
       coalesce(w.running, false)::bool AS work_running,
       coalesce(w.last_status, '')::text AS work_last_status
FROM threads t
LEFT JOIN LATERAL (
    SELECT id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at FROM turns tu WHERE tu.thread_id = t.id ORDER BY tu.started_at DESC LIMIT 1
) lt ON true
LEFT JOIN LATERAL (
    SELECT c.chain_message_id AS chain,
           count(*) AS turns,
           min(c.started_at) AS started_at,
           CASE WHEN bool_or(c.ended_at IS NULL) THEN NULL ELSE max(c.ended_at) END AS ended_at,
           bool_or(c.status = 'running') AS running,
           (SELECT l.status FROM turns l WHERE l.chain_message_id = lt.chain_message_id
            ORDER BY l.ended_at DESC NULLS FIRST, l.started_at DESC LIMIT 1) AS last_status
    FROM turns c
    WHERE c.chain_message_id = lt.chain_message_id
    GROUP BY c.chain_message_id
    HAVING (SELECT o.thread_id FROM turns o WHERE o.chain_message_id = lt.chain_message_id ORDER BY o.started_at LIMIT 1) = t.id
) w ON true
WHERE t.root_message_id = ANY($1::uuid[])
`

type ThreadSummariesRow struct {
	RootMessageID     pgtype.UUID
	ThreadID          pgtype.UUID
	ThreadNumber      int32
	ReplyCount        int64
	LastReplyAt       pgtype.Timestamptz
	TurnCount         int64
	LastTurnID        string
	LastTurnMemberID  string
	LastTurnStatus    string
	LastTurnError     string
	LastTurnStartedAt pgtype.Timestamptz
	LastTurnEndedAt   pgtype.Timestamptz
	WorkChain         string
	WorkTurns         int32
	WorkStartedAt     pgtype.Timestamptz
	WorkEndedAt       pgtype.Timestamptz
	WorkRunning       bool
	WorkLastStatus    string
}

// What the room timeline shows under each topic root: reply count, last
// reply time, the latest turn, and, under the topic where the latest turn's
// piece of work began, that piece of work across all its topics, with how
// it stands by its latest turn: running while one runs, else how the turn
// that ended last ended.
func (q *Queries) ThreadSummaries(ctx context.Context, dollar_1 []pgtype.UUID) ([]ThreadSummariesRow, error) {
	rows, err := q.db.Query(ctx, threadSummaries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThreadSummariesRow
	for rows.Next() {
		var i ThreadSummariesRow
		if err := rows.Scan(
			&i.RootMessageID,
			&i.ThreadID,
			&i.ThreadNumber,
			&i.ReplyCount,
			&i.LastReplyAt,
			&i.TurnCount,
			&i.LastTurnID,
			&i.LastTurnMemberID,
			&i.LastTurnStatus,
			&i.LastTurnError,
			&i.LastTurnStartedAt,
			&i.LastTurnEndedAt,
			&i.WorkChain,
			&i.WorkTurns,
			&i.WorkStartedAt,
			&i.WorkEndedAt,
			&i.WorkRunning,
			&i.WorkLastStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageBody = `-- name: UpdateMessageBody :one
UPDATE messages SET body = $2, turn_id = $3, mentions = $4
WHERE id = $1
RETURNING id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id, title
`

type UpdateMessageBodyParams struct {
	ID       pgtype.UUID
	Body     string
	TurnID   pgtype.UUID
	Mentions []byte
}

// Fills in a topic root once the agent's first reply text is known, with
// whoever that text mentions.
func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageBody,
		arg.ID,
		arg.Body,
		arg.TurnID,
		arg.Mentions,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.MemberID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
		&i.TurnID,
		&i.Title,
	)
	return i, err
}
