// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at
`

type CreateMessageParams struct {
	RoomID          pgtype.UUID
	ThreadID        pgtype.UUID
	SenderKind      string
	UserID          pgtype.UUID
	AgentInstanceID pgtype.UUID
	Body            string
	Mentions        []byte
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.RoomID,
		arg.ThreadID,
		arg.SenderKind,
		arg.UserID,
		arg.AgentInstanceID,
		arg.Body,
		arg.Mentions,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.AgentInstanceID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.AgentInstanceID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
	)
	return i, err
}

const lastAgentMessageInThread = `-- name: LastAgentMessageInThread :one
SELECT id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at FROM messages
WHERE thread_id = $1 AND sender_kind = 'agent'
ORDER BY seq DESC
LIMIT 1
`

// The most recent agent reply in a thread; used to pick who answers a
// message that mentions nobody.
func (q *Queries) LastAgentMessageInThread(ctx context.Context, threadID pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, lastAgentMessageInThread, threadID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.AgentInstanceID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomMessagesAfter = `-- name: ListRoomMessagesAfter :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at FROM messages
WHERE room_id = $1 AND thread_id IS NULL AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListRoomMessagesAfterParams struct {
	RoomID pgtype.UUID
	Seq    int64
	Limit  int32
}

// Top-level messages of a room newer than a cursor, oldest first.
func (q *Queries) ListRoomMessagesAfter(ctx context.Context, arg ListRoomMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRoomMessagesAfter, arg.RoomID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.AgentInstanceID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomMessagesBefore = `-- name: ListRoomMessagesBefore :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at FROM messages
WHERE room_id = $1 AND thread_id IS NULL AND seq < $2
ORDER BY seq DESC
LIMIT $3
`

type ListRoomMessagesBeforeParams struct {
	RoomID pgtype.UUID
	Seq    int64
	Limit  int32
}

// Top-level messages of a room older than a cursor, newest first; callers
// reverse the page to present it chronologically.
func (q *Queries) ListRoomMessagesBefore(ctx context.Context, arg ListRoomMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRoomMessagesBefore, arg.RoomID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.AgentInstanceID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessagesAfter = `-- name: ListThreadMessagesAfter :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at FROM messages
WHERE thread_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListThreadMessagesAfterParams struct {
	ThreadID pgtype.UUID
	Seq      int64
	Limit    int32
}

// Replies in a thread newer than a cursor, oldest first. The root message
// is not a reply and is fetched separately.
func (q *Queries) ListThreadMessagesAfter(ctx context.Context, arg ListThreadMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listThreadMessagesAfter, arg.ThreadID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.AgentInstanceID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessagesBefore = `-- name: ListThreadMessagesBefore :many
SELECT id, seq, room_id, thread_id, sender_kind, user_id, agent_instance_id, body, mentions, created_at FROM messages
WHERE thread_id = $1 AND seq < $2
ORDER BY seq DESC
LIMIT $3
`

type ListThreadMessagesBeforeParams struct {
	ThreadID pgtype.UUID
	Seq      int64
	Limit    int32
}

// The most recent replies in a thread, newest first; callers reverse the
// page to present it chronologically.
func (q *Queries) ListThreadMessagesBefore(ctx context.Context, arg ListThreadMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listThreadMessagesBefore, arg.ThreadID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.RoomID,
			&i.ThreadID,
			&i.SenderKind,
			&i.UserID,
			&i.AgentInstanceID,
			&i.Body,
			&i.Mentions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
