// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentInstance struct {
	ID               pgtype.UUID
	RoomID           pgtype.UUID
	TemplateID       pgtype.UUID
	WorkerID         pgtype.UUID
	DisplayName      string
	RepoPath         string
	BranchMode       string
	Model            string
	PermissionPreset string
	EngineSessionRef string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
}

type AgentTemplate struct {
	ID               pgtype.UUID
	Name             string
	Engine           string
	Model            string
	RoleCard         string
	PermissionPreset string
	EngineOptions    []byte
	Builtin          bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Approval struct {
	ID              pgtype.UUID
	TurnID          pgtype.UUID
	RoomID          pgtype.UUID
	ThreadID        pgtype.UUID
	AgentInstanceID pgtype.UUID
	RequestID       string
	Kind            string
	Payload         []byte
	Status          string
	Message         string
	MessageID       pgtype.UUID
	DecidedBy       pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	DecidedAt       pgtype.Timestamptz
}

type Message struct {
	ID              pgtype.UUID
	Seq             int64
	RoomID          pgtype.UUID
	ThreadID        pgtype.UUID
	SenderKind      string
	UserID          pgtype.UUID
	AgentInstanceID pgtype.UUID
	Body            string
	Mentions        []byte
	CreatedAt       pgtype.Timestamptz
}

type Project struct {
	ID            pgtype.UUID
	Name          string
	RepoUrl       string
	DefaultBranch string
	CreatedAt     pgtype.Timestamptz
}

type Room struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type Thread struct {
	ID            pgtype.UUID
	RoomID        pgtype.UUID
	RootMessageID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type Turn struct {
	ID               pgtype.UUID
	AgentInstanceID  pgtype.UUID
	RoomID           pgtype.UUID
	ThreadID         pgtype.UUID
	TriggerMessageID pgtype.UUID
	WorkerID         pgtype.UUID
	Status           string
	Error            string
	ReplyMessageID   pgtype.UUID
	TranscriptPath   string
	StartedAt        pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Worker struct {
	ID             pgtype.UUID
	Name           string
	Engines        []byte
	ConnectedAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	DisconnectedAt pgtype.Timestamptz
}
