// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID               pgtype.UUID
	Name             string
	Avatar           string
	MachineID        pgtype.UUID
	Runtime          string
	Model            string
	RoleCard         string
	PermissionPreset string
	RuntimeOptions   []byte
	Skills           []string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Approval struct {
	ID           pgtype.UUID
	TurnID       pgtype.UUID
	RoomID       pgtype.UUID
	ThreadID     pgtype.UUID
	MemberID     pgtype.UUID
	RequestID    string
	Kind         string
	Payload      []byte
	SimilarOffer []byte
	Scope        string
	Status       string
	Message      string
	MessageID    pgtype.UUID
	DecidedBy    pgtype.UUID
	Reviewer     string
	Answer       []byte
	CreatedAt    pgtype.Timestamptz
	DecidedAt    pgtype.Timestamptz
}

type Attachment struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	MessageID pgtype.UUID
	Filename  string
	MediaType string
	Size      int64
	Path      string
	CreatedAt pgtype.Timestamptz
}

type InboxRead struct {
	UserID    pgtype.UUID
	MessageID pgtype.UUID
	ReadAt    pgtype.Timestamptz
}

type Machine struct {
	ID             pgtype.UUID
	Name           string
	Runtimes       []byte
	ConnectedAt    pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	DisconnectedAt pgtype.Timestamptz
}

type Member struct {
	ID               pgtype.UUID
	RoomID           pgtype.UUID
	AgentID          pgtype.UUID
	MachineID        pgtype.UUID
	DisplayName      string
	RepoPath         string
	BranchMode       string
	WorktreeDir      string
	WorkDir          string
	Branch           string
	PreparedAt       pgtype.Timestamptz
	OverlapsNoted    []string
	Model            string
	PermissionPreset string
	Enabled          bool
	CreatedAt        pgtype.Timestamptz
	RemovedAt        pgtype.Timestamptz
}

type MemberRule struct {
	ID         pgtype.UUID
	MemberID   pgtype.UUID
	Runtime    string
	Rule       string
	ApprovalID pgtype.UUID
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type MemberSession struct {
	ID          pgtype.UUID
	MemberID    pgtype.UUID
	Runtime     string
	MachineID   pgtype.UUID
	WorkDir     string
	SessionRef  string
	RoomSeen    int64
	ThreadSeen  []byte
	Compactions int32
	WikiSeen    pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	EndReason   string
}

type Message struct {
	ID         pgtype.UUID
	Seq        int64
	RoomID     pgtype.UUID
	ThreadID   pgtype.UUID
	SenderKind string
	UserID     pgtype.UUID
	MemberID   pgtype.UUID
	Body       string
	Mentions   []byte
	CreatedAt  pgtype.Timestamptz
	TurnID     pgtype.UUID
}

type Project struct {
	ID                        pgtype.UUID
	Name                      string
	RepoPath                  string
	Description               string
	WikiSlug                  string
	WikiUpkeep                bool
	WikiMaintainerTrigger     string
	WikiOfferDeclinedAt       pgtype.Timestamptz
	WikiSeenSeq               int64
	WikiExternalBundles       []string
	WorkspaceCopy             []string
	WorkspaceRun              string
	WorkspacePending          []byte
	InitializedAt             pgtype.Timestamptz
	RelayLimit                int32
	CreatedAt                 pgtype.Timestamptz
	WikiMaintainerMemberID    pgtype.UUID
	LeaderMemberID            pgtype.UUID
	WikiThreadID              pgtype.UUID
	WikiOfferMessageID        pgtype.UUID
	SetupThreadID             pgtype.UUID
	WorkspacePendingMessageID pgtype.UUID
}

type RelayHold struct {
	MessageID        pgtype.UUID
	MemberID         pgtype.UUID
	ThreadID         pgtype.UUID
	TriggerMessageID pgtype.UUID
	Reason           string
	CreatedAt        pgtype.Timestamptz
	ContinuedAt      pgtype.Timestamptz
}

type Room struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Name             string
	Kind             string
	LastThreadNumber int32
	CreatedAt        pgtype.Timestamptz
}

type SkillTrial struct {
	ID          pgtype.UUID
	Skill       string
	BaseSha     string
	StartedAt   pgtype.Timestamptz
	ChangedAt   pgtype.Timestamptz
	TurnID      pgtype.UUID
	ChangedBy   string
	ProjectName string
	Changes     int32
	Status      string
	EndedBy     string
	EndedAt     pgtype.Timestamptz
	Reason      string
}

type Thread struct {
	ID            pgtype.UUID
	RoomID        pgtype.UUID
	RootMessageID pgtype.UUID
	Number        int32
	CreatedAt     pgtype.Timestamptz
}

type Turn struct {
	ID               pgtype.UUID
	MemberID         pgtype.UUID
	RoomID           pgtype.UUID
	ThreadID         pgtype.UUID
	TriggerMessageID pgtype.UUID
	MachineID        pgtype.UUID
	SessionID        pgtype.UUID
	Runtime          string
	Kind             string
	Status           string
	Error            string
	ReplyMessageID   pgtype.UUID
	TranscriptPath   string
	InputTokens      int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	OutputTokens     int64
	FilesChanged     []string
	SkillsUsed       []string
	ChainMessageID   pgtype.UUID
	WokenByTurnID    pgtype.UUID
	Worked           bool
	TrustedBy        pgtype.UUID
	TrustedAt        pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type WikiReview struct {
	ProjectID    pgtype.UUID
	TurnID       pgtype.UUID
	UpkeepTurnID pgtype.UUID
	ReviewedAt   pgtype.Timestamptz
}
