// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const continueRelayHold = `-- name: ContinueRelayHold :one
UPDATE relay_holds SET continued_at = now()
WHERE message_id = $1 AND continued_at IS NULL
RETURNING message_id, member_id, thread_id, trigger_message_id, reason, created_at, continued_at
`

// Lets a held wake go on, once.
func (q *Queries) ContinueRelayHold(ctx context.Context, messageID pgtype.UUID) (RelayHold, error) {
	row := q.db.QueryRow(ctx, continueRelayHold, messageID)
	var i RelayHold
	err := row.Scan(
		&i.MessageID,
		&i.MemberID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.Reason,
		&i.CreatedAt,
		&i.ContinuedAt,
	)
	return i, err
}

const createRelayHold = `-- name: CreateRelayHold :exec
INSERT INTO relay_holds (message_id, member_id, thread_id, trigger_message_id, reason)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRelayHoldParams struct {
	MessageID        pgtype.UUID
	MemberID         pgtype.UUID
	ThreadID         pgtype.UUID
	TriggerMessageID pgtype.UUID
	Reason           string
}

func (q *Queries) CreateRelayHold(ctx context.Context, arg CreateRelayHoldParams) error {
	_, err := q.db.Exec(ctx, createRelayHold,
		arg.MessageID,
		arg.MemberID,
		arg.ThreadID,
		arg.TriggerMessageID,
		arg.Reason,
	)
	return err
}

const getRelayHold = `-- name: GetRelayHold :one
SELECT message_id, member_id, thread_id, trigger_message_id, reason, created_at, continued_at FROM relay_holds WHERE message_id = $1
`

func (q *Queries) GetRelayHold(ctx context.Context, messageID pgtype.UUID) (RelayHold, error) {
	row := q.db.QueryRow(ctx, getRelayHold, messageID)
	var i RelayHold
	err := row.Scan(
		&i.MessageID,
		&i.MemberID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.Reason,
		&i.CreatedAt,
		&i.ContinuedAt,
	)
	return i, err
}

const listThreadRelayHolds = `-- name: ListThreadRelayHolds :many
SELECT h.message_id, h.member_id, h.thread_id, h.trigger_message_id, h.reason, h.created_at, h.continued_at FROM relay_holds h
JOIN messages m ON m.id = h.message_id
WHERE m.thread_id = $1
ORDER BY h.created_at
`

// The wakes held back that notes in a topic tell of.
func (q *Queries) ListThreadRelayHolds(ctx context.Context, threadID pgtype.UUID) ([]RelayHold, error) {
	rows, err := q.db.Query(ctx, listThreadRelayHolds, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelayHold
	for rows.Next() {
		var i RelayHold
		if err := rows.Scan(
			&i.MessageID,
			&i.MemberID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.Reason,
			&i.CreatedAt,
			&i.ContinuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
