// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roomread.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getThreadByNumber = `-- name: GetThreadByNumber :one

SELECT id, room_id, root_message_id, number, created_at FROM threads WHERE room_id = $1 AND number = $2
`

type GetThreadByNumberParams struct {
	RoomID pgtype.UUID
	Number int32
}

// What an agent reads of its room on request (the read tools, design.md
// 5.7): the directory of topics, a topic by its number, a search.
func (q *Queries) GetThreadByNumber(ctx context.Context, arg GetThreadByNumberParams) (Thread, error) {
	row := q.db.QueryRow(ctx, getThreadByNumber, arg.RoomID, arg.Number)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RootMessageID,
		&i.Number,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomTopics = `-- name: ListRoomTopics :many
SELECT x.thread_id, x.number, x.reply_count, x.last_seq, r.id, r.seq, r.room_id, r.thread_id, r.sender_kind, r.user_id, r.member_id, r.body, r.mentions, r.created_at, r.turn_id, l.id, l.seq, l.room_id, l.thread_id, l.sender_kind, l.user_id, l.member_id, l.body, l.mentions, l.created_at, l.turn_id
FROM (
    SELECT t.id AS thread_id, t.number, t.root_message_id,
           (SELECT count(*) FROM messages m WHERE m.thread_id = t.id) AS reply_count,
           coalesce((SELECT max(m.seq) FROM messages m WHERE m.thread_id = t.id), rm.seq)::bigint AS last_seq
    FROM threads t
    JOIN messages rm ON rm.id = t.root_message_id
    WHERE t.room_id = $1
) x
JOIN messages r ON r.id = x.root_message_id
JOIN messages l ON l.seq = x.last_seq
WHERE x.last_seq < $2::bigint
ORDER BY x.last_seq DESC
LIMIT $3
`

type ListRoomTopicsParams struct {
	RoomID  pgtype.UUID
	Before  int64
	MaxRows int32
}

type ListRoomTopicsRow struct {
	ThreadID   pgtype.UUID
	Number     int32
	ReplyCount int64
	LastSeq    int64
	Message    Message
	Message_2  Message
}

// A room's topics, most recently active first, older than a cursor: how
// many replies each has, its root, and its last message (the root itself
// while nobody has replied).
func (q *Queries) ListRoomTopics(ctx context.Context, arg ListRoomTopicsParams) ([]ListRoomTopicsRow, error) {
	rows, err := q.db.Query(ctx, listRoomTopics, arg.RoomID, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomTopicsRow
	for rows.Next() {
		var i ListRoomTopicsRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Number,
			&i.ReplyCount,
			&i.LastSeq,
			&i.Message.ID,
			&i.Message.Seq,
			&i.Message.RoomID,
			&i.Message.ThreadID,
			&i.Message.SenderKind,
			&i.Message.UserID,
			&i.Message.MemberID,
			&i.Message.Body,
			&i.Message.Mentions,
			&i.Message.CreatedAt,
			&i.Message.TurnID,
			&i.Message_2.ID,
			&i.Message_2.Seq,
			&i.Message_2.RoomID,
			&i.Message_2.ThreadID,
			&i.Message_2.SenderKind,
			&i.Message_2.UserID,
			&i.Message_2.MemberID,
			&i.Message_2.Body,
			&i.Message_2.Mentions,
			&i.Message_2.CreatedAt,
			&i.Message_2.TurnID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRoomMessages = `-- name: SearchRoomMessages :many
SELECT m.id, m.seq, m.room_id, m.thread_id, m.sender_kind, m.user_id, m.member_id, m.body, m.mentions, m.created_at, m.turn_id, coalesce(t.number, rt.number, 0)::int AS topic_number
FROM messages m
LEFT JOIN threads t ON t.id = m.thread_id
LEFT JOIN threads rt ON rt.root_message_id = m.id
WHERE m.room_id = $1
  AND m.body ILIKE $2::text
  AND m.seq < $3::bigint
ORDER BY m.seq DESC
LIMIT $4
`

type SearchRoomMessagesParams struct {
	RoomID  pgtype.UUID
	Pattern string
	Before  int64
	MaxRows int32
}

type SearchRoomMessagesRow struct {
	Message     Message
	TopicNumber int32
}

// Messages of a room whose text holds a phrase, newest first, each with
// the number of the topic it is in or heads (0 for neither). The pattern
// arrives escaped, wildcards included.
func (q *Queries) SearchRoomMessages(ctx context.Context, arg SearchRoomMessagesParams) ([]SearchRoomMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchRoomMessages,
		arg.RoomID,
		arg.Pattern,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRoomMessagesRow
	for rows.Next() {
		var i SearchRoomMessagesRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.Seq,
			&i.Message.RoomID,
			&i.Message.ThreadID,
			&i.Message.SenderKind,
			&i.Message.UserID,
			&i.Message.MemberID,
			&i.Message.Body,
			&i.Message.Mentions,
			&i.Message.CreatedAt,
			&i.Message.TurnID,
			&i.TopicNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
