// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (project_id, name, kind)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, kind, last_thread_number, created_at
`

type CreateRoomParams struct {
	ProjectID pgtype.UUID
	Name      string
	Kind      string
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.ProjectID, arg.Name, arg.Kind)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.LastThreadNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, project_id, name, kind, last_thread_number, created_at FROM rooms WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.LastThreadNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomsByProject = `-- name: ListRoomsByProject :many
SELECT id, project_id, name, kind, last_thread_number, created_at FROM rooms
WHERE project_id = $1
ORDER BY (kind = 'main') DESC, created_at
`

// The main room comes first, then topic rooms in creation order.
func (q *Queries) ListRoomsByProject(ctx context.Context, projectID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRoomsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.LastThreadNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
