// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMemberRule = `-- name: AddMemberRule :one
INSERT INTO member_rules (member_id, runtime, rule, approval_id, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (member_id, runtime, rule) DO UPDATE SET rule = member_rules.rule
RETURNING id, member_id, runtime, rule, approval_id, created_by, created_at
`

type AddMemberRuleParams struct {
	MemberID   pgtype.UUID
	Runtime    string
	Rule       string
	ApprovalID pgtype.UUID
	CreatedBy  pgtype.UUID
}

// A rule is kept once: allowing the same one again leaves the first as it
// was, and returns it.
func (q *Queries) AddMemberRule(ctx context.Context, arg AddMemberRuleParams) (MemberRule, error) {
	row := q.db.QueryRow(ctx, addMemberRule,
		arg.MemberID,
		arg.Runtime,
		arg.Rule,
		arg.ApprovalID,
		arg.CreatedBy,
	)
	var i MemberRule
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Runtime,
		&i.Rule,
		&i.ApprovalID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMemberRule = `-- name: DeleteMemberRule :execrows
DELETE FROM member_rules WHERE member_id = $1 AND id = $2
`

type DeleteMemberRuleParams struct {
	MemberID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) DeleteMemberRule(ctx context.Context, arg DeleteMemberRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMemberRule, arg.MemberID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMemberRules = `-- name: ListMemberRules :many
SELECT id, member_id, runtime, rule, approval_id, created_by, created_at FROM member_rules
WHERE member_id = $1
  AND ($2::text IS NULL OR runtime = $2::text)
ORDER BY created_at, rule
`

type ListMemberRulesParams struct {
	MemberID pgtype.UUID
	Runtime  pgtype.Text
}

// What a member may always ask for without a person being asked, oldest
// first: every runtime's, or only the one named.
func (q *Queries) ListMemberRules(ctx context.Context, arg ListMemberRulesParams) ([]MemberRule, error) {
	rows, err := q.db.Query(ctx, listMemberRules, arg.MemberID, arg.Runtime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberRule
	for rows.Next() {
		var i MemberRule
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Runtime,
			&i.Rule,
			&i.ApprovalID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
