// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSession = `-- name: AdvanceSession :execrows
UPDATE member_sessions SET
    room_seen   = GREATEST(room_seen, $1::bigint),
    thread_seen = thread_seen || jsonb_build_object(
        $2::text,
        GREATEST(coalesce((thread_seen ->> $2::text)::bigint, 0), $3::bigint)),
    wiki_seen   = GREATEST(wiki_seen, $4::timestamptz)
WHERE id = $5
`

type AdvanceSessionParams struct {
	RoomSeen   int64
	ThreadID   string
	ThreadSeen int64
	WikiSeen   pgtype.Timestamptz
	ID         pgtype.UUID
}

// Moves a session's reading positions forward after a turn that took its
// brief in: the room's, the one topic's it was briefed in, and the project
// wiki's when the brief showed it (NULL leaves it). Positions never move
// back.
func (q *Queries) AdvanceSession(ctx context.Context, arg AdvanceSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceSession,
		arg.RoomSeen,
		arg.ThreadID,
		arg.ThreadSeen,
		arg.WikiSeen,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSessionTurns = `-- name: CountSessionTurns :one
SELECT count(*) FROM turns WHERE session_id = $1
`

// How many turns have run in a session.
func (q *Queries) CountSessionTurns(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionTurns, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO member_sessions (id, member_id, runtime, machine_id, work_dir, session_ref)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, member_id, runtime, machine_id, work_dir, session_ref, room_seen, thread_seen, compactions, wiki_seen, started_at, ended_at, end_reason
`

type CreateSessionParams struct {
	ID         pgtype.UUID
	MemberID   pgtype.UUID
	Runtime    string
	MachineID  pgtype.UUID
	WorkDir    string
	SessionRef string
}

// The id comes from the caller: the hub hands it to the runtime as the
// session's name before the row exists.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (MemberSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.MemberID,
		arg.Runtime,
		arg.MachineID,
		arg.WorkDir,
		arg.SessionRef,
	)
	var i MemberSession
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Runtime,
		&i.MachineID,
		&i.WorkDir,
		&i.SessionRef,
		&i.RoomSeen,
		&i.ThreadSeen,
		&i.Compactions,
		&i.WikiSeen,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const endOpenSession = `-- name: EndOpenSession :execrows
UPDATE member_sessions SET ended_at = now(), end_reason = $2
WHERE member_id = $1 AND ended_at IS NULL
`

type EndOpenSessionParams struct {
	MemberID  pgtype.UUID
	EndReason string
}

// Ends the member's open session, if it has one, and says why.
func (q *Queries) EndOpenSession(ctx context.Context, arg EndOpenSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, endOpenSession, arg.MemberID, arg.EndReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOpenSession = `-- name: GetOpenSession :one
SELECT id, member_id, runtime, machine_id, work_dir, session_ref, room_seen, thread_seen, compactions, wiki_seen, started_at, ended_at, end_reason FROM member_sessions WHERE member_id = $1 AND ended_at IS NULL
`

// The session a member's next turn resumes; no row when it has none.
func (q *Queries) GetOpenSession(ctx context.Context, memberID pgtype.UUID) (MemberSession, error) {
	row := q.db.QueryRow(ctx, getOpenSession, memberID)
	var i MemberSession
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Runtime,
		&i.MachineID,
		&i.WorkDir,
		&i.SessionRef,
		&i.RoomSeen,
		&i.ThreadSeen,
		&i.Compactions,
		&i.WikiSeen,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, member_id, runtime, machine_id, work_dir, session_ref, room_seen, thread_seen, compactions, wiki_seen, started_at, ended_at, end_reason FROM member_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (MemberSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i MemberSession
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Runtime,
		&i.MachineID,
		&i.WorkDir,
		&i.SessionRef,
		&i.RoomSeen,
		&i.ThreadSeen,
		&i.Compactions,
		&i.WikiSeen,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
	)
	return i, err
}

const listMemberSessions = `-- name: ListMemberSessions :many
SELECT id, member_id, runtime, machine_id, work_dir, session_ref, room_seen, thread_seen, compactions, wiki_seen, started_at, ended_at, end_reason FROM member_sessions WHERE member_id = $1 ORDER BY started_at DESC, id
`

// Every session a member has had, newest first.
func (q *Queries) ListMemberSessions(ctx context.Context, memberID pgtype.UUID) ([]MemberSession, error) {
	rows, err := q.db.Query(ctx, listMemberSessions, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberSession
	for rows.Next() {
		var i MemberSession
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Runtime,
			&i.MachineID,
			&i.WorkDir,
			&i.SessionRef,
			&i.RoomSeen,
			&i.ThreadSeen,
			&i.Compactions,
			&i.WikiSeen,
			&i.StartedAt,
			&i.EndedAt,
			&i.EndReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberHasRunningTurn = `-- name: MemberHasRunningTurn :one
SELECT EXISTS (SELECT 1 FROM turns WHERE member_id = $1 AND status = 'running')
`

func (q *Queries) MemberHasRunningTurn(ctx context.Context, memberID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, memberHasRunningTurn, memberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const noteSessionCompactions = `-- name: NoteSessionCompactions :execrows
UPDATE member_sessions SET
    compactions = compactions + $1::int,
    thread_seen = '{}'::jsonb,
    wiki_seen   = NULL
WHERE id = $2
`

type NoteSessionCompactionsParams struct {
	Count int32
	ID    pgtype.UUID
}

// Counts compactions the runtime reported and forgets what the session had
// read of each topic and of the wiki's catalog, as the session itself just
// did with the detail.
func (q *Queries) NoteSessionCompactions(ctx context.Context, arg NoteSessionCompactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, noteSessionCompactions, arg.Count, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionRef = `-- name: SetSessionRef :execrows
UPDATE member_sessions SET session_ref = $2 WHERE id = $1
`

type SetSessionRefParams struct {
	ID         pgtype.UUID
	SessionRef string
}

// Stores the runtime's own reference to the session as soon as it is known.
func (q *Queries) SetSessionRef(ctx context.Context, arg SetSessionRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionRef, arg.ID, arg.SessionRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
