// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getThread = `-- name: GetThread :one
SELECT id, room_id, root_message_id, created_at FROM threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id pgtype.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RootMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertThread = `-- name: UpsertThread :one
INSERT INTO threads (room_id, root_message_id)
VALUES ($1, $2)
ON CONFLICT (root_message_id) DO UPDATE SET root_message_id = EXCLUDED.root_message_id
RETURNING id, room_id, root_message_id, created_at
`

type UpsertThreadParams struct {
	RoomID        pgtype.UUID
	RootMessageID pgtype.UUID
}

// Creates the thread rooted at a message, or returns the existing one. The
// no-op update makes RETURNING yield the row in both cases.
func (q *Queries) UpsertThread(ctx context.Context, arg UpsertThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, upsertThread, arg.RoomID, arg.RootMessageID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.RootMessageID,
		&i.CreatedAt,
	)
	return i, err
}
