// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const endSkillTrial = `-- name: EndSkillTrial :one
UPDATE skill_trials
SET status = $1, ended_by = $2, ended_at = now(), reason = $3
WHERE id = $4 AND status = 'open'
RETURNING id, skill, base_sha, started_at, changed_at, turn_id, changed_by, project_name, changes, status, ended_by, ended_at, reason
`

type EndSkillTrialParams struct {
	Status  string
	EndedBy string
	Reason  string
	ID      pgtype.UUID
}

func (q *Queries) EndSkillTrial(ctx context.Context, arg EndSkillTrialParams) (SkillTrial, error) {
	row := q.db.QueryRow(ctx, endSkillTrial,
		arg.Status,
		arg.EndedBy,
		arg.Reason,
		arg.ID,
	)
	var i SkillTrial
	err := row.Scan(
		&i.ID,
		&i.Skill,
		&i.BaseSha,
		&i.StartedAt,
		&i.ChangedAt,
		&i.TurnID,
		&i.ChangedBy,
		&i.ProjectName,
		&i.Changes,
		&i.Status,
		&i.EndedBy,
		&i.EndedAt,
		&i.Reason,
	)
	return i, err
}

const latestSkillTrial = `-- name: LatestSkillTrial :one
SELECT id, skill, base_sha, started_at, changed_at, turn_id, changed_by, project_name, changes, status, ended_by, ended_at, reason FROM skill_trials
WHERE skill = $1
ORDER BY (status = 'open') DESC, started_at DESC
LIMIT 1
`

// The skill's open trial, or else the one that ended last.
func (q *Queries) LatestSkillTrial(ctx context.Context, skill string) (SkillTrial, error) {
	row := q.db.QueryRow(ctx, latestSkillTrial, skill)
	var i SkillTrial
	err := row.Scan(
		&i.ID,
		&i.Skill,
		&i.BaseSha,
		&i.StartedAt,
		&i.ChangedAt,
		&i.TurnID,
		&i.ChangedBy,
		&i.ProjectName,
		&i.Changes,
		&i.Status,
		&i.EndedBy,
		&i.EndedAt,
		&i.Reason,
	)
	return i, err
}

const listOpenSkillTrials = `-- name: ListOpenSkillTrials :many
SELECT id, skill, base_sha, started_at, changed_at, turn_id, changed_by, project_name, changes, status, ended_by, ended_at, reason FROM skill_trials
WHERE status = 'open' AND skill = ANY ($1::text[])
ORDER BY started_at
`

// The open trials of the skills named, oldest first.
func (q *Queries) ListOpenSkillTrials(ctx context.Context, skills []string) ([]SkillTrial, error) {
	rows, err := q.db.Query(ctx, listOpenSkillTrials, skills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillTrial
	for rows.Next() {
		var i SkillTrial
		if err := rows.Scan(
			&i.ID,
			&i.Skill,
			&i.BaseSha,
			&i.StartedAt,
			&i.ChangedAt,
			&i.TurnID,
			&i.ChangedBy,
			&i.ProjectName,
			&i.Changes,
			&i.Status,
			&i.EndedBy,
			&i.EndedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openSkillTrial = `-- name: OpenSkillTrial :one
SELECT id, skill, base_sha, started_at, changed_at, turn_id, changed_by, project_name, changes, status, ended_by, ended_at, reason FROM skill_trials WHERE skill = $1 AND status = 'open'
`

func (q *Queries) OpenSkillTrial(ctx context.Context, skill string) (SkillTrial, error) {
	row := q.db.QueryRow(ctx, openSkillTrial, skill)
	var i SkillTrial
	err := row.Scan(
		&i.ID,
		&i.Skill,
		&i.BaseSha,
		&i.StartedAt,
		&i.ChangedAt,
		&i.TurnID,
		&i.ChangedBy,
		&i.ProjectName,
		&i.Changes,
		&i.Status,
		&i.EndedBy,
		&i.EndedAt,
		&i.Reason,
	)
	return i, err
}

const skillTrialUses = `-- name: SkillTrialUses :one
SELECT count(*) FILTER (WHERE status = 'done')::integer AS done,
       count(*) FILTER (WHERE status = 'failed')::integer AS failed
FROM turns
WHERE $1::text = ANY (skills_used) AND started_at > $2
`

type SkillTrialUsesParams struct {
	Skill string
	Since pgtype.Timestamptz
}

type SkillTrialUsesRow struct {
	Done   int32
	Failed int32
}

// How the turns that used a skill since it last changed ended; a turn that
// began before the change used the version before.
func (q *Queries) SkillTrialUses(ctx context.Context, arg SkillTrialUsesParams) (SkillTrialUsesRow, error) {
	row := q.db.QueryRow(ctx, skillTrialUses, arg.Skill, arg.Since)
	var i SkillTrialUsesRow
	err := row.Scan(&i.Done, &i.Failed)
	return i, err
}

const startSkillTrial = `-- name: StartSkillTrial :one
INSERT INTO skill_trials (skill, base_sha, turn_id, changed_by, project_name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (skill) WHERE status = 'open' DO UPDATE
SET changed_at = now(), turn_id = EXCLUDED.turn_id, changed_by = EXCLUDED.changed_by,
    project_name = EXCLUDED.project_name, changes = skill_trials.changes + 1
RETURNING id, skill, base_sha, started_at, changed_at, turn_id, changed_by, project_name, changes, status, ended_by, ended_at, reason
`

type StartSkillTrialParams struct {
	Skill       string
	BaseSha     string
	TurnID      pgtype.UUID
	ChangedBy   string
	ProjectName string
}

// A change to a skill (design.md 5.15): opens its trial, or, when one is
// open, starts its count again from the same version to go back to.
func (q *Queries) StartSkillTrial(ctx context.Context, arg StartSkillTrialParams) (SkillTrial, error) {
	row := q.db.QueryRow(ctx, startSkillTrial,
		arg.Skill,
		arg.BaseSha,
		arg.TurnID,
		arg.ChangedBy,
		arg.ProjectName,
	)
	var i SkillTrial
	err := row.Scan(
		&i.ID,
		&i.Skill,
		&i.BaseSha,
		&i.StartedAt,
		&i.ChangedAt,
		&i.TurnID,
		&i.ChangedBy,
		&i.ProjectName,
		&i.Changes,
		&i.Status,
		&i.EndedBy,
		&i.EndedAt,
		&i.Reason,
	)
	return i, err
}
