// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns (agent_instance_id, room_id, thread_id, trigger_message_id, worker_id, transcript_path)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, agent_instance_id, room_id, thread_id, trigger_message_id, worker_id, status, error, reply_message_id, transcript_path, started_at, ended_at
`

type CreateTurnParams struct {
	AgentInstanceID  pgtype.UUID
	RoomID           pgtype.UUID
	ThreadID         pgtype.UUID
	TriggerMessageID pgtype.UUID
	WorkerID         pgtype.UUID
	TranscriptPath   string
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.AgentInstanceID,
		arg.RoomID,
		arg.ThreadID,
		arg.TriggerMessageID,
		arg.WorkerID,
		arg.TranscriptPath,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.AgentInstanceID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.WorkerID,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const finishTurn = `-- name: FinishTurn :one
UPDATE turns SET
    status           = $2,
    error            = $3,
    reply_message_id = $4,
    transcript_path  = $5,
    ended_at         = now()
WHERE id = $1
RETURNING id, agent_instance_id, room_id, thread_id, trigger_message_id, worker_id, status, error, reply_message_id, transcript_path, started_at, ended_at
`

type FinishTurnParams struct {
	ID             pgtype.UUID
	Status         string
	Error          string
	ReplyMessageID pgtype.UUID
	TranscriptPath string
}

func (q *Queries) FinishTurn(ctx context.Context, arg FinishTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, finishTurn,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.ReplyMessageID,
		arg.TranscriptPath,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.AgentInstanceID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.WorkerID,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, agent_instance_id, room_id, thread_id, trigger_message_id, worker_id, status, error, reply_message_id, transcript_path, started_at, ended_at FROM turns WHERE id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.AgentInstanceID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.WorkerID,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listRoomTurns = `-- name: ListRoomTurns :many
SELECT id, agent_instance_id, room_id, thread_id, trigger_message_id, worker_id, status, error, reply_message_id, transcript_path, started_at, ended_at FROM turns WHERE room_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListRoomTurnsParams struct {
	RoomID pgtype.UUID
	Limit  int32
}

// Most recent turns of a room first.
func (q *Queries) ListRoomTurns(ctx context.Context, arg ListRoomTurnsParams) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listRoomTurns, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.AgentInstanceID,
			&i.RoomID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.WorkerID,
			&i.Status,
			&i.Error,
			&i.ReplyMessageID,
			&i.TranscriptPath,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
