// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: turns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReminder = `-- name: CancelReminder :one
UPDATE reminders SET status = 'cancelled', cancelled_by = $1, settled_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at
`

type CancelReminderParams struct {
	CancelledBy pgtype.UUID
	ID          pgtype.UUID
}

// Takes back a reminder not yet due, by a person when cancelled_by is set.
func (q *Queries) CancelReminder(ctx context.Context, arg CancelReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, cancelReminder, arg.CancelledBy, arg.ID)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TurnID,
		&i.Note,
		&i.DueAt,
		&i.Status,
		&i.SetMessageID,
		&i.FiredMessageID,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const claimDraft = `-- name: ClaimDraft :one
UPDATE drafts SET status = 'running' WHERE id = $1 AND status = 'pending'
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

// A person runs a pending draft: one run at a time, and none once it is
// settled.
func (q *Queries) ClaimDraft(ctx context.Context, id pgtype.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, claimDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const clearTurnTrust = `-- name: ClearTurnTrust :one
UPDATE turns SET trusted_by = NULL, trusted_at = NULL
WHERE id = $1
RETURNING id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at
`

// A person takes it back. A turn that ended trusted keeps who trusted it,
// as a record: nothing is let through once it is over.
func (q *Queries) ClearTurnTrust(ctx context.Context, id pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, clearTurnTrust, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.WikiPages,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const countChainWakes = `-- name: CountChainWakes :one
SELECT count(*) FROM turns WHERE chain_message_id = $1 AND woken_by_turn_id IS NOT NULL
`

// The turns agents woke in a piece of work, under way or over.
func (q *Queries) CountChainWakes(ctx context.Context, chainMessageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChainWakes, chainMessageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingReminders = `-- name: CountPendingReminders :one
SELECT count(*) FROM reminders WHERE member_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingReminders(ctx context.Context, memberID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReminders, memberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTurnDrafts = `-- name: CountTurnDrafts :one
SELECT count(*) FROM drafts WHERE turn_id = $1
`

func (q *Queries) CountTurnDrafts(ctx context.Context, turnID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTurnDrafts, turnID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDraft = `-- name: CreateDraft :one
INSERT INTO drafts (project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10)
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

type CreateDraftParams struct {
	ProjectID pgtype.UUID
	RoomID    pgtype.UUID
	ThreadID  pgtype.UUID
	MemberID  pgtype.UUID
	TurnID    pgtype.UUID
	Kind      string
	TargetID  pgtype.UUID
	Subject   string
	Params    []byte
	ThenNote  string
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.ProjectID,
		arg.RoomID,
		arg.ThreadID,
		arg.MemberID,
		arg.TurnID,
		arg.Kind,
		arg.TargetID,
		arg.Subject,
		arg.Params,
		arg.ThenNote,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (member_id, room_id, thread_id, turn_id, note, due_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at
`

type CreateReminderParams struct {
	MemberID pgtype.UUID
	RoomID   pgtype.UUID
	ThreadID pgtype.UUID
	TurnID   pgtype.UUID
	Note     string
	DueAt    pgtype.Timestamptz
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.MemberID,
		arg.RoomID,
		arg.ThreadID,
		arg.TurnID,
		arg.Note,
		arg.DueAt,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TurnID,
		&i.Note,
		&i.DueAt,
		&i.Status,
		&i.SetMessageID,
		&i.FiredMessageID,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns (member_id, room_id, thread_id, trigger_message_id, machine_id, runtime, transcript_path, session_id, kind, chain_message_id, woken_by_turn_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at
`

type CreateTurnParams struct {
	MemberID         pgtype.UUID
	RoomID           pgtype.UUID
	ThreadID         pgtype.UUID
	TriggerMessageID pgtype.UUID
	MachineID        pgtype.UUID
	Runtime          string
	TranscriptPath   string
	SessionID        pgtype.UUID
	Kind             string
	ChainMessageID   pgtype.UUID
	WokenByTurnID    pgtype.UUID
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.MemberID,
		arg.RoomID,
		arg.ThreadID,
		arg.TriggerMessageID,
		arg.MachineID,
		arg.Runtime,
		arg.TranscriptPath,
		arg.SessionID,
		arg.Kind,
		arg.ChainMessageID,
		arg.WokenByTurnID,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.WikiPages,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const declineDraft = `-- name: DeclineDraft :one
UPDATE drafts SET status = 'declined', decided_by = $1, settled_at = now()
WHERE id = $2 AND status = 'pending'
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

type DeclineDraftParams struct {
	DecidedBy pgtype.UUID
	ID        pgtype.UUID
}

// A person turns a pending draft down.
func (q *Queries) DeclineDraft(ctx context.Context, arg DeclineDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, declineDraft, arg.DecidedBy, arg.ID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const dropReminder = `-- name: DropReminder :one
UPDATE reminders SET status = 'dropped', settled_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at
`

// A reminder whose member is gone or switched off as it comes due.
func (q *Queries) DropReminder(ctx context.Context, id pgtype.UUID) (Reminder, error) {
	row := q.db.QueryRow(ctx, dropReminder, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TurnID,
		&i.Note,
		&i.DueAt,
		&i.Status,
		&i.SetMessageID,
		&i.FiredMessageID,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const failRunningTurns = `-- name: FailRunningTurns :many
UPDATE turns SET status = 'failed', error = $1, ended_at = now()
WHERE status = 'running'
RETURNING id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at
`

// Turns still marked running when the hub starts were cut off by its last
// stop; nothing will ever finish them.
func (q *Queries) FailRunningTurns(ctx context.Context, error string) ([]Turn, error) {
	rows, err := q.db.Query(ctx, failRunningTurns, error)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.MachineID,
			&i.SessionID,
			&i.Runtime,
			&i.Kind,
			&i.Status,
			&i.Error,
			&i.ReplyMessageID,
			&i.TranscriptPath,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.OutputTokens,
			&i.FilesChanged,
			&i.SkillsUsed,
			&i.WikiPages,
			&i.ChainMessageID,
			&i.WokenByTurnID,
			&i.Worked,
			&i.TrustedBy,
			&i.TrustedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishTurn = `-- name: FinishTurn :one
UPDATE turns SET
    status             = $2,
    error              = $3,
    reply_message_id   = $4,
    transcript_path    = $5,
    input_tokens       = $6,
    cache_read_tokens  = $7,
    cache_write_tokens = $8,
    output_tokens      = $9,
    files_changed      = $10,
    skills_used        = $11,
    worked             = $12,
    wiki_pages         = $13,
    ended_at           = now()
WHERE id = $1
RETURNING id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at
`

type FinishTurnParams struct {
	ID               pgtype.UUID
	Status           string
	Error            string
	ReplyMessageID   pgtype.UUID
	TranscriptPath   string
	InputTokens      int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	OutputTokens     int64
	FilesChanged     []string
	SkillsUsed       []string
	Worked           bool
	WikiPages        []string
}

func (q *Queries) FinishTurn(ctx context.Context, arg FinishTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, finishTurn,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.ReplyMessageID,
		arg.TranscriptPath,
		arg.InputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.OutputTokens,
		arg.FilesChanged,
		arg.SkillsUsed,
		arg.Worked,
		arg.WikiPages,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.WikiPages,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const fireReminder = `-- name: FireReminder :one
UPDATE reminders SET status = 'fired', settled_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at
`

// A reminder comes due, once: one fired or cancelled already is left as it
// is, and nothing comes back.
func (q *Queries) FireReminder(ctx context.Context, id pgtype.UUID) (Reminder, error) {
	row := q.db.QueryRow(ctx, fireReminder, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TurnID,
		&i.Note,
		&i.DueAt,
		&i.Status,
		&i.SetMessageID,
		&i.FiredMessageID,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getDraft = `-- name: GetDraft :one
SELECT id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at FROM drafts WHERE id = $1
`

func (q *Queries) GetDraft(ctx context.Context, id pgtype.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getDraftByMessage = `-- name: GetDraftByMessage :one
SELECT id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at FROM drafts WHERE message_id = $1 OR result_message_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// The draft a message is the card or the outcome of.
func (q *Queries) GetDraftByMessage(ctx context.Context, messageID pgtype.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraftByMessage, messageID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getReminder = `-- name: GetReminder :one
SELECT id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at FROM reminders WHERE id = $1
`

func (q *Queries) GetReminder(ctx context.Context, id pgtype.UUID) (Reminder, error) {
	row := q.db.QueryRow(ctx, getReminder, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TurnID,
		&i.Note,
		&i.DueAt,
		&i.Status,
		&i.SetMessageID,
		&i.FiredMessageID,
		&i.CancelledBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getTurn = `-- name: GetTurn :one
SELECT id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at FROM turns WHERE id = $1
`

func (q *Queries) GetTurn(ctx context.Context, id pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, getTurn, id)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.WikiPages,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const liftAccountPause = `-- name: LiftAccountPause :execrows
DELETE FROM pauses WHERE member_id IS NULL AND machine_id = $1 AND runtime = $2
`

type LiftAccountPauseParams struct {
	MachineID pgtype.UUID
	Runtime   string
}

func (q *Queries) LiftAccountPause(ctx context.Context, arg LiftAccountPauseParams) (int64, error) {
	result, err := q.db.Exec(ctx, liftAccountPause, arg.MachineID, arg.Runtime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liftMemberPause = `-- name: LiftMemberPause :execrows
DELETE FROM pauses WHERE member_id = $1
`

func (q *Queries) LiftMemberPause(ctx context.Context, memberID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, liftMemberPause, memberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMachineTurnsSince = `-- name: ListMachineTurnsSince :many
SELECT status, started_at, ended_at, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens
FROM turns
WHERE machine_id = $1
  AND started_at >= $2
  AND ($3::text = '' OR runtime = $3::text)
ORDER BY started_at
`

type ListMachineTurnsSinceParams struct {
	MachineID pgtype.UUID
	Since     pgtype.Timestamptz
	Runtime   string
}

type ListMachineTurnsSinceRow struct {
	Status           string
	StartedAt        pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
	InputTokens      int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	OutputTokens     int64
}

// How a machine's turns since a moment went: when each started, how it
// ended and when, and the tokens it spent; only one runtime's unless runtime
// is empty. The machines page sums them into hours or days.
func (q *Queries) ListMachineTurnsSince(ctx context.Context, arg ListMachineTurnsSinceParams) ([]ListMachineTurnsSinceRow, error) {
	rows, err := q.db.Query(ctx, listMachineTurnsSince, arg.MachineID, arg.Since, arg.Runtime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachineTurnsSinceRow
	for rows.Next() {
		var i ListMachineTurnsSinceRow
		if err := rows.Scan(
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.OutputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberPendingReminders = `-- name: ListMemberPendingReminders :many
SELECT id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at FROM reminders WHERE member_id = $1 AND status = 'pending' ORDER BY due_at, id
`

func (q *Queries) ListMemberPendingReminders(ctx context.Context, memberID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listMemberPendingReminders, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TurnID,
			&i.Note,
			&i.DueAt,
			&i.Status,
			&i.SetMessageID,
			&i.FiredMessageID,
			&i.CancelledBy,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPauses = `-- name: ListPauses :many
SELECT id, machine_id, runtime, member_id, reason, detail, ends_at, created_at FROM pauses ORDER BY created_at, id
`

// The pauses in effect, the oldest first.
func (q *Queries) ListPauses(ctx context.Context) ([]Pause, error) {
	rows, err := q.db.Query(ctx, listPauses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pause
	for rows.Next() {
		var i Pause
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Runtime,
			&i.MemberID,
			&i.Reason,
			&i.Detail,
			&i.EndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReminders = `-- name: ListPendingReminders :many
SELECT r.id, r.member_id, r.room_id, r.thread_id, r.turn_id, r.note, r.due_at, r.status, r.set_message_id, r.fired_message_id, r.cancelled_by, r.created_at, r.settled_at FROM reminders r
JOIN members m ON m.id = r.member_id
WHERE m.machine_id = $1 AND r.status = 'pending'
ORDER BY r.due_at, r.id
`

// The reminders not yet due of the members a machine runs, the soonest
// first.
func (q *Queries) ListPendingReminders(ctx context.Context, machineID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listPendingReminders, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TurnID,
			&i.Note,
			&i.DueAt,
			&i.Status,
			&i.SetMessageID,
			&i.FiredMessageID,
			&i.CancelledBy,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedWakes = `-- name: ListQueuedWakes :many
SELECT q.member_id, q.message_id, q.thread_id, q.anchor_id, q.queued_at FROM queued_wakes q
JOIN members m ON m.id = q.member_id
WHERE m.machine_id = $1
ORDER BY q.queued_at, q.message_id
`

// What the members running on a machine were asked and wait for, in the
// order they were asked.
func (q *Queries) ListQueuedWakes(ctx context.Context, machineID pgtype.UUID) ([]QueuedWake, error) {
	rows, err := q.db.Query(ctx, listQueuedWakes, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueuedWake
	for rows.Next() {
		var i QueuedWake
		if err := rows.Scan(
			&i.MemberID,
			&i.MessageID,
			&i.ThreadID,
			&i.AnchorID,
			&i.QueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTurns = `-- name: ListRoomTurns :many
SELECT id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at FROM turns WHERE room_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListRoomTurnsParams struct {
	RoomID pgtype.UUID
	Limit  int32
}

// Most recent turns of a room first.
func (q *Queries) ListRoomTurns(ctx context.Context, arg ListRoomTurnsParams) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listRoomTurns, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.MachineID,
			&i.SessionID,
			&i.Runtime,
			&i.Kind,
			&i.Status,
			&i.Error,
			&i.ReplyMessageID,
			&i.TranscriptPath,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.OutputTokens,
			&i.FilesChanged,
			&i.SkillsUsed,
			&i.WikiPages,
			&i.ChainMessageID,
			&i.WokenByTurnID,
			&i.Worked,
			&i.TrustedBy,
			&i.TrustedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTurnsByStatus = `-- name: ListRoomTurnsByStatus :many
SELECT id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at FROM turns WHERE room_id = $1 AND status = $2 ORDER BY started_at DESC LIMIT $3
`

type ListRoomTurnsByStatusParams struct {
	RoomID pgtype.UUID
	Status string
	Limit  int32
}

// Most recent turns of a room in one status first; the UI opens a room
// with only the running ones.
func (q *Queries) ListRoomTurnsByStatus(ctx context.Context, arg ListRoomTurnsByStatusParams) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listRoomTurnsByStatus, arg.RoomID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.MachineID,
			&i.SessionID,
			&i.Runtime,
			&i.Kind,
			&i.Status,
			&i.Error,
			&i.ReplyMessageID,
			&i.TranscriptPath,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.OutputTokens,
			&i.FilesChanged,
			&i.SkillsUsed,
			&i.WikiPages,
			&i.ChainMessageID,
			&i.WokenByTurnID,
			&i.Worked,
			&i.TrustedBy,
			&i.TrustedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningTopics = `-- name: ListRunningTopics :many
SELECT t.id AS thread_id, t.room_id, t.root_message_id, m.body AS root_body,
       array_agg(DISTINCT mb.display_name)::text[] AS members,
       min(tu.started_at)::timestamptz AS started_at,
       -- What the topic was asked: the words that set its first turn off,
       -- and the names of the room's members, whose @s lead them.
       coalesce((SELECT a.body FROM turns ft JOIN messages a ON a.id = ft.trigger_message_id
                 WHERE ft.thread_id = t.id ORDER BY ft.started_at LIMIT 1), '')::text AS ask,
       coalesce((SELECT array_agg(rm.display_name) FROM members rm WHERE rm.room_id = t.room_id), '{}')::text[] AS names
FROM turns tu
JOIN threads t ON t.id = tu.thread_id
JOIN messages m ON m.id = t.root_message_id
JOIN members mb ON mb.id = tu.member_id
WHERE tu.status = 'running'
GROUP BY t.id, t.room_id, t.root_message_id, m.body
ORDER BY started_at
`

type ListRunningTopicsRow struct {
	ThreadID      pgtype.UUID
	RoomID        pgtype.UUID
	RootMessageID pgtype.UUID
	RootBody      string
	Members       []string
	StartedAt     pgtype.Timestamptz
	Ask           string
	Names         []string
}

// The topics with a turn in flight, across every room: what the sidebar
// lists under each project while its members work.
func (q *Queries) ListRunningTopics(ctx context.Context) ([]ListRunningTopicsRow, error) {
	rows, err := q.db.Query(ctx, listRunningTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningTopicsRow
	for rows.Next() {
		var i ListRunningTopicsRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.RoomID,
			&i.RootMessageID,
			&i.RootBody,
			&i.Members,
			&i.StartedAt,
			&i.Ask,
			&i.Names,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillUses = `-- name: ListSkillUses :many
SELECT t.id, t.status, t.runtime, t.started_at, t.ended_at, t.room_id, t.thread_id,
       th.number AS topic_number, m.display_name AS member_name, p.id AS project_id, p.name AS project_name
FROM turns t
JOIN threads th ON th.id = t.thread_id
JOIN members m ON m.id = t.member_id
JOIN rooms r ON r.id = t.room_id
JOIN projects p ON p.id = r.project_id
WHERE $1::text = ANY (t.skills_used)
ORDER BY t.started_at DESC, t.id
LIMIT $2
`

type ListSkillUsesParams struct {
	Skill string
	Lim   int32
}

type ListSkillUsesRow struct {
	ID          pgtype.UUID
	Status      string
	Runtime     string
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	RoomID      pgtype.UUID
	ThreadID    pgtype.UUID
	TopicNumber int32
	MemberName  string
	ProjectID   pgtype.UUID
	ProjectName string
}

// The turns that used a skill, newest first, with where they ran: what the
// team that owns it looks back on.
func (q *Queries) ListSkillUses(ctx context.Context, arg ListSkillUsesParams) ([]ListSkillUsesRow, error) {
	rows, err := q.db.Query(ctx, listSkillUses, arg.Skill, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillUsesRow
	for rows.Next() {
		var i ListSkillUsesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Runtime,
			&i.StartedAt,
			&i.EndedAt,
			&i.RoomID,
			&i.ThreadID,
			&i.TopicNumber,
			&i.MemberName,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadDrafts = `-- name: ListThreadDrafts :many
SELECT id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at FROM drafts WHERE thread_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListThreadDrafts(ctx context.Context, threadID pgtype.UUID) ([]Draft, error) {
	rows, err := q.db.Query(ctx, listThreadDrafts, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RoomID,
			&i.ThreadID,
			&i.MemberID,
			&i.TurnID,
			&i.Kind,
			&i.TargetID,
			&i.Subject,
			&i.Params,
			&i.ThenNote,
			&i.Status,
			&i.Result,
			&i.MessageID,
			&i.ResultMessageID,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadReminders = `-- name: ListThreadReminders :many
SELECT id, member_id, room_id, thread_id, turn_id, note, due_at, status, set_message_id, fired_message_id, cancelled_by, created_at, settled_at FROM reminders WHERE thread_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListThreadReminders(ctx context.Context, threadID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listThreadReminders, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TurnID,
			&i.Note,
			&i.DueAt,
			&i.Status,
			&i.SetMessageID,
			&i.FiredMessageID,
			&i.CancelledBy,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadTurns = `-- name: ListThreadTurns :many
SELECT id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at FROM turns
WHERE thread_id = $1
ORDER BY started_at
`

// Every turn of a topic, oldest first, so a thread can be read turn by turn.
func (q *Queries) ListThreadTurns(ctx context.Context, threadID pgtype.UUID) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listThreadTurns, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.MachineID,
			&i.SessionID,
			&i.Runtime,
			&i.Kind,
			&i.Status,
			&i.Error,
			&i.ReplyMessageID,
			&i.TranscriptPath,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.OutputTokens,
			&i.FilesChanged,
			&i.SkillsUsed,
			&i.WikiPages,
			&i.ChainMessageID,
			&i.WokenByTurnID,
			&i.Worked,
			&i.TrustedBy,
			&i.TrustedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDraftSubject = `-- name: LockDraftSubject :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ' ' || $2::text, 0))
`

type LockDraftSubjectParams struct {
	ProjectID string
	Subject   string
}

// Holds a project's drafts about a subject for the transaction: those
// drafted at once give way one to another in turn.
func (q *Queries) LockDraftSubject(ctx context.Context, arg LockDraftSubjectParams) error {
	_, err := q.db.Exec(ctx, lockDraftSubject, arg.ProjectID, arg.Subject)
	return err
}

const openDraft = `-- name: OpenDraft :one
SELECT id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at FROM drafts
WHERE project_id = $1 AND subject = $2 AND status IN ('pending', 'running')
ORDER BY created_at DESC
LIMIT 1
`

type OpenDraftParams struct {
	ProjectID pgtype.UUID
	Subject   string
}

// The project's draft about subject that is not settled yet.
func (q *Queries) OpenDraft(ctx context.Context, arg OpenDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, openDraft, arg.ProjectID, arg.Subject)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const pauseAccount = `-- name: PauseAccount :one
INSERT INTO pauses (machine_id, runtime, reason, detail, ends_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (machine_id, runtime) WHERE member_id IS NULL DO UPDATE SET
    reason = EXCLUDED.reason, detail = EXCLUDED.detail, ends_at = EXCLUDED.ends_at
RETURNING id, machine_id, runtime, member_id, reason, detail, ends_at, created_at
`

type PauseAccountParams struct {
	MachineID pgtype.UUID
	Runtime   string
	Reason    string
	Detail    string
	EndsAt    pgtype.Timestamptz
}

// Pauses a runtime's account on a machine, or updates why and until when:
// it keeps the time it began.
func (q *Queries) PauseAccount(ctx context.Context, arg PauseAccountParams) (Pause, error) {
	row := q.db.QueryRow(ctx, pauseAccount,
		arg.MachineID,
		arg.Runtime,
		arg.Reason,
		arg.Detail,
		arg.EndsAt,
	)
	var i Pause
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Runtime,
		&i.MemberID,
		&i.Reason,
		&i.Detail,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const pauseMember = `-- name: PauseMember :one
INSERT INTO pauses (member_id, reason, detail, ends_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (member_id) WHERE member_id IS NOT NULL DO UPDATE SET
    reason = EXCLUDED.reason, detail = EXCLUDED.detail, ends_at = EXCLUDED.ends_at
RETURNING id, machine_id, runtime, member_id, reason, detail, ends_at, created_at
`

type PauseMemberParams struct {
	MemberID pgtype.UUID
	Reason   string
	Detail   string
	EndsAt   pgtype.Timestamptz
}

// Pauses a member, or updates why and until when.
func (q *Queries) PauseMember(ctx context.Context, arg PauseMemberParams) (Pause, error) {
	row := q.db.QueryRow(ctx, pauseMember,
		arg.MemberID,
		arg.Reason,
		arg.Detail,
		arg.EndsAt,
	)
	var i Pause
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Runtime,
		&i.MemberID,
		&i.Reason,
		&i.Detail,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const queueWake = `-- name: QueueWake :exec
INSERT INTO queued_wakes (member_id, message_id, thread_id, anchor_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type QueueWakeParams struct {
	MemberID  pgtype.UUID
	MessageID pgtype.UUID
	ThreadID  pgtype.UUID
	AnchorID  pgtype.UUID
}

// Keeps what a busy member was asked until its turn starts; asked twice
// by one message, it waits once.
func (q *Queries) QueueWake(ctx context.Context, arg QueueWakeParams) error {
	_, err := q.db.Exec(ctx, queueWake,
		arg.MemberID,
		arg.MessageID,
		arg.ThreadID,
		arg.AnchorID,
	)
	return err
}

const recentChainWakes = `-- name: RecentChainWakes :many
SELECT worked FROM turns
WHERE chain_message_id = $1 AND woken_by_turn_id IS NOT NULL AND ended_at IS NOT NULL
ORDER BY ended_at DESC
LIMIT $2
`

type RecentChainWakesParams struct {
	ChainMessageID pgtype.UUID
	Limit          int32
}

// Whether the last turns agents woke in a piece of work to end did work,
// the latest first.
func (q *Queries) RecentChainWakes(ctx context.Context, arg RecentChainWakesParams) ([]bool, error) {
	rows, err := q.db.Query(ctx, recentChainWakes, arg.ChainMessageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []bool
	for rows.Next() {
		var worked bool
		if err := rows.Scan(&worked); err != nil {
			return nil, err
		}
		items = append(items, worked)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDraft = `-- name: ReleaseDraft :one
UPDATE drafts SET status = 'pending' WHERE id = $1 AND status = 'running'
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

// A run that could not be done for now: the draft waits again.
func (q *Queries) ReleaseDraft(ctx context.Context, id pgtype.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, releaseDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const releaseRunningDrafts = `-- name: ReleaseRunningDrafts :many
UPDATE drafts SET status = 'pending' WHERE status = 'running'
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

// Runs a stopped hub left under way wait again; what they did shows when
// run again.
func (q *Queries) ReleaseRunningDrafts(ctx context.Context) ([]Draft, error) {
	rows, err := q.db.Query(ctx, releaseRunningDrafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RoomID,
			&i.ThreadID,
			&i.MemberID,
			&i.TurnID,
			&i.Kind,
			&i.TargetID,
			&i.Subject,
			&i.Params,
			&i.ThenNote,
			&i.Status,
			&i.Result,
			&i.MessageID,
			&i.ResultMessageID,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runningMembersInThread = `-- name: RunningMembersInThread :many
SELECT DISTINCT member_id FROM turns WHERE thread_id = $1 AND status = 'running'
`

// The members with a turn running in a topic, getting ready included: a
// person's message there that mentions nobody goes to the one running
// (design.md 4.2).
func (q *Queries) RunningMembersInThread(ctx context.Context, threadID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, runningMembersInThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var member_id pgtype.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDraftMessage = `-- name: SetDraftMessage :exec
UPDATE drafts SET message_id = $1 WHERE id = $2
`

type SetDraftMessageParams struct {
	MessageID pgtype.UUID
	ID        pgtype.UUID
}

// The card that shows a draft.
func (q *Queries) SetDraftMessage(ctx context.Context, arg SetDraftMessageParams) error {
	_, err := q.db.Exec(ctx, setDraftMessage, arg.MessageID, arg.ID)
	return err
}

const setDraftResultMessage = `-- name: SetDraftResultMessage :exec
UPDATE drafts SET result_message_id = $1 WHERE id = $2
`

type SetDraftResultMessageParams struct {
	MessageID pgtype.UUID
	ID        pgtype.UUID
}

// The message that told the member what came of its draft.
func (q *Queries) SetDraftResultMessage(ctx context.Context, arg SetDraftResultMessageParams) error {
	_, err := q.db.Exec(ctx, setDraftResultMessage, arg.MessageID, arg.ID)
	return err
}

const setReminderFired = `-- name: SetReminderFired :exec
UPDATE reminders SET fired_message_id = $1 WHERE id = $2
`

type SetReminderFiredParams struct {
	MessageID pgtype.UUID
	ID        pgtype.UUID
}

// The message a reminder came due as.
func (q *Queries) SetReminderFired(ctx context.Context, arg SetReminderFiredParams) error {
	_, err := q.db.Exec(ctx, setReminderFired, arg.MessageID, arg.ID)
	return err
}

const setReminderMessage = `-- name: SetReminderMessage :exec
UPDATE reminders SET set_message_id = $1 WHERE id = $2
`

type SetReminderMessageParams struct {
	MessageID pgtype.UUID
	ID        pgtype.UUID
}

// The note that told of a reminder as it was set.
func (q *Queries) SetReminderMessage(ctx context.Context, arg SetReminderMessageParams) error {
	_, err := q.db.Exec(ctx, setReminderMessage, arg.MessageID, arg.ID)
	return err
}

const setTurnSession = `-- name: SetTurnSession :execrows
UPDATE turns SET session_id = $2 WHERE id = $1
`

type SetTurnSessionParams struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
}

// Moves a running turn to another session: the one it started in would not
// resume, and the turn was run again in a new one.
func (q *Queries) SetTurnSession(ctx context.Context, arg SetTurnSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTurnSession, arg.ID, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTurnTrust = `-- name: SetTurnTrust :one
UPDATE turns SET trusted_by = $2, trusted_at = now()
WHERE id = $1 AND status = 'running'
RETURNING id, member_id, room_id, thread_id, trigger_message_id, machine_id, session_id, runtime, kind, status, error, reply_message_id, transcript_path, input_tokens, cache_read_tokens, cache_write_tokens, output_tokens, files_changed, skills_used, wiki_pages, chain_message_id, woken_by_turn_id, worked, trusted_by, trusted_at, started_at, ended_at
`

type SetTurnTrustParams struct {
	ID        pgtype.UUID
	TrustedBy pgtype.UUID
}

// A person lets the rest of a running turn's requests through.
func (q *Queries) SetTurnTrust(ctx context.Context, arg SetTurnTrustParams) (Turn, error) {
	row := q.db.QueryRow(ctx, setTurnTrust, arg.ID, arg.TrustedBy)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.WikiPages,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const settleDraft = `-- name: SettleDraft :one
UPDATE drafts SET status = $1, result = $2, decided_by = $3, settled_at = now()
WHERE id = $4 AND status = 'running'
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

type SettleDraftParams struct {
	Status    string
	Result    []byte
	DecidedBy pgtype.UUID
	ID        pgtype.UUID
}

// What came of a run: done, or conflicted.
func (q *Queries) SettleDraft(ctx context.Context, arg SettleDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, settleDraft,
		arg.Status,
		arg.Result,
		arg.DecidedBy,
		arg.ID,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RoomID,
		&i.ThreadID,
		&i.MemberID,
		&i.TurnID,
		&i.Kind,
		&i.TargetID,
		&i.Subject,
		&i.Params,
		&i.ThenNote,
		&i.Status,
		&i.Result,
		&i.MessageID,
		&i.ResultMessageID,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const supersedeDrafts = `-- name: SupersedeDrafts :many
UPDATE drafts SET status = 'superseded', settled_at = now()
WHERE project_id = $1 AND subject = $2 AND status = 'pending'
RETURNING id, project_id, room_id, thread_id, member_id, turn_id, kind, target_id, subject, params, then_note, status, result, message_id, result_message_id, decided_by, created_at, settled_at
`

type SupersedeDraftsParams struct {
	ProjectID pgtype.UUID
	Subject   string
}

// The project's pending drafts about subject give way to a new one.
func (q *Queries) SupersedeDrafts(ctx context.Context, arg SupersedeDraftsParams) ([]Draft, error) {
	rows, err := q.db.Query(ctx, supersedeDrafts, arg.ProjectID, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Draft
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RoomID,
			&i.ThreadID,
			&i.MemberID,
			&i.TurnID,
			&i.Kind,
			&i.TargetID,
			&i.Subject,
			&i.Params,
			&i.ThenNote,
			&i.Status,
			&i.Result,
			&i.MessageID,
			&i.ResultMessageID,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const turnAtSessionEnd = `-- name: TurnAtSessionEnd :one
SELECT t.id, t.member_id, t.room_id, t.thread_id, t.trigger_message_id, t.machine_id, t.session_id, t.runtime, t.kind, t.status, t.error, t.reply_message_id, t.transcript_path, t.input_tokens, t.cache_read_tokens, t.cache_write_tokens, t.output_tokens, t.files_changed, t.skills_used, t.wiki_pages, t.chain_message_id, t.woken_by_turn_id, t.worked, t.trusted_by, t.trusted_at, t.started_at, t.ended_at FROM turns t JOIN member_sessions s ON s.member_id = t.member_id
WHERE s.id = $1 AND t.member_id = $2 AND t.started_at <= s.ended_at
ORDER BY t.started_at DESC LIMIT 1
`

type TurnAtSessionEndParams struct {
	SessionID pgtype.UUID
	MemberID  pgtype.UUID
}

// The member's latest turn by the time one of its sessions ended: the one
// going as the session ended, which may not have got a session yet.
func (q *Queries) TurnAtSessionEnd(ctx context.Context, arg TurnAtSessionEndParams) (Turn, error) {
	row := q.db.QueryRow(ctx, turnAtSessionEnd, arg.SessionID, arg.MemberID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.WikiPages,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const unqueueWakes = `-- name: UnqueueWakes :exec
DELETE FROM queued_wakes
WHERE member_id = $1 AND message_id = ANY($2::uuid[])
`

type UnqueueWakesParams struct {
	MemberID   pgtype.UUID
	MessageIds []pgtype.UUID
}

// A turn started for these messages: they wait no longer.
func (q *Queries) UnqueueWakes(ctx context.Context, arg UnqueueWakesParams) error {
	_, err := q.db.Exec(ctx, unqueueWakes, arg.MemberID, arg.MessageIds)
	return err
}
