// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upkeep.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPeopleWaiting = `-- name: CountPeopleWaiting :one
SELECT count(*)::bigint AS people,
       count(*) FILTER (
           WHERE m.created_at <= $1::timestamptz
             AND (m.thread_id IS NULL OR (
                 NOT EXISTS (SELECT 1 FROM messages x WHERE x.thread_id = m.thread_id AND x.created_at > $1::timestamptz)
                 AND NOT EXISTS (SELECT 1 FROM turns t WHERE t.thread_id = m.thread_id AND t.status = 'running')))
       )::bigint AS settled
FROM messages m
JOIN rooms r ON r.id = m.room_id AND r.kind = 'main'
JOIN projects p ON p.id = r.project_id
WHERE r.project_id = $2 AND m.sender_kind = 'user' AND m.seq > p.wiki_seen_seq
`

type CountPeopleWaitingParams struct {
	QuietSince pgtype.Timestamptz
	ProjectID  pgtype.UUID
}

type CountPeopleWaitingRow struct {
	People  int64
	Settled int64
}

// What people said in a project's chat that its wiki maintainer has not
// gone over (design.md 5.16): their messages in the main room, the chat
// the maintainer reads and keeps files from, after the project's wiki
// position, and how many of them were settled by quiet_since: said by
// then, in the room itself or in a topic nothing was said in after and no
// turn runs in.
func (q *Queries) CountPeopleWaiting(ctx context.Context, arg CountPeopleWaitingParams) (CountPeopleWaitingRow, error) {
	row := q.db.QueryRow(ctx, countPeopleWaiting, arg.QuietSince, arg.ProjectID)
	var i CountPeopleWaitingRow
	err := row.Scan(&i.People, &i.Settled)
	return i, err
}

const countSettledTopicsWaiting = `-- name: CountSettledTopicsWaiting :one
SELECT count(DISTINCT t.thread_id)::bigint
FROM turns t
JOIN rooms r ON r.id = t.room_id
WHERE r.project_id = $1 AND t.status <> 'running' AND t.kind = 'chat'
  AND t.ended_at <= $2::timestamptz
  AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.thread_id = t.thread_id AND m.created_at > $2::timestamptz)
  AND NOT EXISTS (SELECT 1 FROM turns x WHERE x.thread_id = t.thread_id AND x.status = 'running')
  AND NOT EXISTS (SELECT 1 FROM wiki_reviews w WHERE w.project_id = $1 AND w.turn_id = t.id)
`

type CountSettledTopicsWaitingParams struct {
	ProjectID  pgtype.UUID
	QuietSince pgtype.Timestamptz
}

// The topics of a project's own chat that went quiet by quiet_since with
// turns its wiki maintainer has not gone over: what a maintainer is offered
// on (design.md 5.16).
func (q *Queries) CountSettledTopicsWaiting(ctx context.Context, arg CountSettledTopicsWaitingParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSettledTopicsWaiting, arg.ProjectID, arg.QuietSince)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUpkeepReviews = `-- name: CountUpkeepReviews :one
SELECT count(*)::bigint FROM wiki_reviews WHERE upkeep_turn_id = $1
`

// How many turns an upkeep went over.
func (q *Queries) CountUpkeepReviews(ctx context.Context, upkeepTurnID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUpkeepReviews, upkeepTurnID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUpkeepWaiting = `-- name: CountUpkeepWaiting :one
SELECT count(*) FILTER (WHERE r.project_id = $1)::bigint AS own,
       count(*) FILTER (WHERE r.project_id <> $1)::bigint AS uses,
       count(*) FILTER (
           WHERE t.ended_at <= $2::timestamptz
             AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.thread_id = t.thread_id AND m.created_at > $2::timestamptz)
             AND NOT EXISTS (SELECT 1 FROM turns x WHERE x.thread_id = t.thread_id AND x.status = 'running')
       )::bigint AS settled
FROM turns t
JOIN rooms r ON r.id = t.room_id
WHERE t.status <> 'running' AND t.kind = 'chat'
  AND (r.project_id = $1 OR t.skills_used && $3::text[])
  AND NOT EXISTS (SELECT 1 FROM wiki_reviews w WHERE w.project_id = $1 AND w.turn_id = t.id)
`

type CountUpkeepWaitingParams struct {
	ProjectID  pgtype.UUID
	QuietSince pgtype.Timestamptz
	Owned      []string
}

type CountUpkeepWaitingRow struct {
	Own     int64
	Uses    int64
	Settled int64
}

// What waits for a project's wiki maintainer: the finished turns it has not
// gone over, its project's own and other projects' that used its team's
// skills, and how many of all those ran in topics settled by quiet_since:
// the turn ended by then, nothing was said in its topic after, and no turn
// runs there.
func (q *Queries) CountUpkeepWaiting(ctx context.Context, arg CountUpkeepWaitingParams) (CountUpkeepWaitingRow, error) {
	row := q.db.QueryRow(ctx, countUpkeepWaiting, arg.ProjectID, arg.QuietSince, arg.Owned)
	var i CountUpkeepWaitingRow
	err := row.Scan(&i.Own, &i.Uses, &i.Settled)
	return i, err
}

const countUpkeepsSince = `-- name: CountUpkeepsSince :one
SELECT count(*)::bigint FROM turns t
JOIN rooms r ON r.id = t.room_id
WHERE r.project_id = $1 AND t.kind = 'upkeep' AND t.started_at >= $2::timestamptz
`

type CountUpkeepsSinceParams struct {
	ProjectID pgtype.UUID
	Since     pgtype.Timestamptz
}

// How many upkeeps of a project's wiki started since a moment.
func (q *Queries) CountUpkeepsSince(ctx context.Context, arg CountUpkeepsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUpkeepsSince, arg.ProjectID, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const lastUpkeep = `-- name: LastUpkeep :one
SELECT t.id, t.member_id, t.room_id, t.thread_id, t.trigger_message_id, t.machine_id, t.session_id, t.runtime, t.kind, t.status, t.error, t.reply_message_id, t.transcript_path, t.input_tokens, t.cache_read_tokens, t.cache_write_tokens, t.output_tokens, t.files_changed, t.skills_used, t.chain_message_id, t.woken_by_turn_id, t.worked, t.trusted_by, t.trusted_at, t.started_at, t.ended_at FROM turns t
JOIN rooms r ON r.id = t.room_id
WHERE r.project_id = $1 AND t.kind = 'upkeep'
ORDER BY t.started_at DESC
LIMIT 1
`

// The latest turn of a project's wiki maintainer, running or not.
func (q *Queries) LastUpkeep(ctx context.Context, projectID pgtype.UUID) (Turn, error) {
	row := q.db.QueryRow(ctx, lastUpkeep, projectID)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.MachineID,
		&i.SessionID,
		&i.Runtime,
		&i.Kind,
		&i.Status,
		&i.Error,
		&i.ReplyMessageID,
		&i.TranscriptPath,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.OutputTokens,
		&i.FilesChanged,
		&i.SkillsUsed,
		&i.ChainMessageID,
		&i.WokenByTurnID,
		&i.Worked,
		&i.TrustedBy,
		&i.TrustedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listChangedFiles = `-- name: ListChangedFiles :many
SELECT DISTINCT ON (f.path) f.path::text AS path, t.id AS turn_id, t.room_id, t.thread_id,
       coalesce(th.number, 0)::integer AS topic_number, t.started_at
FROM turns t
JOIN rooms r ON r.id = t.room_id
CROSS JOIN LATERAL unnest(t.files_changed) AS f(path)
LEFT JOIN threads th ON th.id = t.thread_id
WHERE r.project_id = $1 AND t.started_at > $2::timestamptz
ORDER BY f.path, t.started_at DESC
LIMIT $3
`

type ListChangedFilesParams struct {
	ProjectID pgtype.UUID
	Since     pgtype.Timestamptz
	Lim       int32
}

type ListChangedFilesRow struct {
	Path        string
	TurnID      pgtype.UUID
	RoomID      pgtype.UUID
	ThreadID    pgtype.UUID
	TopicNumber int32
	StartedAt   pgtype.Timestamptz
}

// The files changed by the turns of a project's chat that started after a
// moment, each once, with the last of those turns to start and its topic:
// what a wiki page naming one is checked again for (design.md 5.16). A
// turn is known to have changed a file after a page was written only if it
// started after, which leaves out the turn that wrote the page. Files are
// as the turns recorded them.
func (q *Queries) ListChangedFiles(ctx context.Context, arg ListChangedFilesParams) ([]ListChangedFilesRow, error) {
	rows, err := q.db.Query(ctx, listChangedFiles, arg.ProjectID, arg.Since, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangedFilesRow
	for rows.Next() {
		var i ListChangedFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.TurnID,
			&i.RoomID,
			&i.ThreadID,
			&i.TopicNumber,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleFiles = `-- name: ListPeopleFiles :many
SELECT a.id, a.room_id, a.message_id, a.filename, a.media_type, a.size, a.path, a.created_at,
       coalesce(th.number, 0)::integer AS topic_number, coalesce(u.name, '')::text AS sender
FROM attachments a
JOIN messages m ON m.id = a.message_id
JOIN rooms r ON r.id = m.room_id AND r.kind = 'main'
LEFT JOIN threads th ON th.id = m.thread_id
LEFT JOIN users u ON u.id = m.user_id
WHERE r.project_id = $1 AND m.sender_kind = 'user' AND m.seq > $2 AND m.seq <= $3
ORDER BY m.seq, a.created_at
LIMIT $4
`

type ListPeopleFilesParams struct {
	ProjectID pgtype.UUID
	After     int64
	Upto      int64
	Lim       int32
}

type ListPeopleFilesRow struct {
	ID          pgtype.UUID
	RoomID      pgtype.UUID
	MessageID   pgtype.UUID
	Filename    string
	MediaType   string
	Size        int64
	Path        string
	CreatedAt   pgtype.Timestamptz
	TopicNumber int32
	Sender      string
}

// The files people sent in a project's main room after one position up to
// another, oldest first, with where and by whom.
func (q *Queries) ListPeopleFiles(ctx context.Context, arg ListPeopleFilesParams) ([]ListPeopleFilesRow, error) {
	rows, err := q.db.Query(ctx, listPeopleFiles,
		arg.ProjectID,
		arg.After,
		arg.Upto,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeopleFilesRow
	for rows.Next() {
		var i ListPeopleFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.MessageID,
			&i.Filename,
			&i.MediaType,
			&i.Size,
			&i.Path,
			&i.CreatedAt,
			&i.TopicNumber,
			&i.Sender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleNews = `-- name: ListPeopleNews :many
SELECT m.thread_id, coalesce(th.number, 0)::integer AS topic_number, coalesce(root.body, '')::text AS root_body,
       count(DISTINCT m.id)::bigint AS messages, count(a.id)::bigint AS files, max(m.created_at)::timestamptz AS last_at
FROM messages m
JOIN rooms r ON r.id = m.room_id AND r.kind = 'main'
LEFT JOIN threads th ON th.id = m.thread_id
LEFT JOIN messages root ON root.id = th.root_message_id
LEFT JOIN attachments a ON a.message_id = m.id
WHERE r.project_id = $1 AND m.sender_kind = 'user' AND m.seq > $2 AND m.seq <= $3
GROUP BY m.thread_id, th.number, root.body
ORDER BY max(m.seq)
LIMIT $4
`

type ListPeopleNewsParams struct {
	ProjectID pgtype.UUID
	After     int64
	Upto      int64
	Lim       int32
}

type ListPeopleNewsRow struct {
	ThreadID    pgtype.UUID
	TopicNumber int32
	RootBody    string
	Messages    int64
	Files       int64
	LastAt      pgtype.Timestamptz
}

// What people said in a project's main room after one position up to
// another, by topic (the room itself has topic zero): how many messages,
// how many files they carried, and when the last was said; oldest first.
func (q *Queries) ListPeopleNews(ctx context.Context, arg ListPeopleNewsParams) ([]ListPeopleNewsRow, error) {
	rows, err := q.db.Query(ctx, listPeopleNews,
		arg.ProjectID,
		arg.After,
		arg.Upto,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeopleNewsRow
	for rows.Next() {
		var i ListPeopleNewsRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.TopicNumber,
			&i.RootBody,
			&i.Messages,
			&i.Files,
			&i.LastAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpkeepTurns = `-- name: ListUpkeepTurns :many

SELECT t.id, t.thread_id, t.room_id, th.number AS topic_number, coalesce(root.body, '')::text AS root_body,
       mb.display_name AS member_name, t.runtime, t.status, t.error, t.files_changed, t.skills_used,
       t.started_at, t.ended_at, p.id AS project_id, p.name AS project_name,
       EXISTS (SELECT 1 FROM wiki_reviews w WHERE w.project_id = $1 AND w.turn_id = t.id) AS reviewed
FROM turns t
JOIN threads th ON th.id = t.thread_id
LEFT JOIN messages root ON root.id = th.root_message_id
JOIN members mb ON mb.id = t.member_id
JOIN rooms r ON r.id = t.room_id
JOIN projects p ON p.id = r.project_id
WHERE t.status <> 'running' AND t.kind = 'chat'
  AND CASE WHEN $2::boolean
           THEN r.project_id <> $1 AND t.skills_used && $3::text[]
           ELSE r.project_id = $1 END
  AND ($4::integer = 0 OR th.number = $4::integer)
  AND (NOT $5::boolean
       OR NOT EXISTS (SELECT 1 FROM wiki_reviews w WHERE w.project_id = $1 AND w.turn_id = t.id))
  AND ($6::timestamptz IS NULL OR (
          t.ended_at <= $6::timestamptz
          AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.thread_id = t.thread_id AND m.created_at > $6::timestamptz)
          AND NOT EXISTS (SELECT 1 FROM turns x WHERE x.thread_id = t.thread_id AND x.status = 'running')))
  AND ($7::timestamptz IS NULL OR t.started_at < $7::timestamptz)
ORDER BY CASE WHEN $8::boolean THEN t.started_at END ASC, t.started_at DESC, t.id
LIMIT $9
`

type ListUpkeepTurnsParams struct {
	ProjectID   pgtype.UUID
	Skills      bool
	Owned       []string
	Topic       int32
	Unreviewed  bool
	SettledBy   pgtype.Timestamptz
	Before      pgtype.Timestamptz
	OldestFirst bool
	Lim         int32
}

type ListUpkeepTurnsRow struct {
	ID           pgtype.UUID
	ThreadID     pgtype.UUID
	RoomID       pgtype.UUID
	TopicNumber  int32
	RootBody     string
	MemberName   string
	Runtime      string
	Status       string
	Error        string
	FilesChanged []string
	SkillsUsed   []string
	StartedAt    pgtype.Timestamptz
	EndedAt      pgtype.Timestamptz
	ProjectID    pgtype.UUID
	ProjectName  string
	Reviewed     bool
}

// The wiki maintainer's bookkeeping (docs/design.md 5.12): which turns a
// project's maintainer looks at, which it has gone over, when it last ran.
// Finished turns a project's wiki maintainer may look at: the project's own
// that answered its chat, or with skills set, other projects' turns that
// used one of the skills its team owns. unreviewed keeps the ones its
// maintainer has not gone over; topic keeps one topic of the project's
// chat (zero keeps all); settled_by keeps the ones in topics settled by
// then (see CountUpkeepWaiting); before pages back. The maintainer's brief
// reads them oldest first, list_turns newest first.
func (q *Queries) ListUpkeepTurns(ctx context.Context, arg ListUpkeepTurnsParams) ([]ListUpkeepTurnsRow, error) {
	rows, err := q.db.Query(ctx, listUpkeepTurns,
		arg.ProjectID,
		arg.Skills,
		arg.Owned,
		arg.Topic,
		arg.Unreviewed,
		arg.SettledBy,
		arg.Before,
		arg.OldestFirst,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpkeepTurnsRow
	for rows.Next() {
		var i ListUpkeepTurnsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.RoomID,
			&i.TopicNumber,
			&i.RootBody,
			&i.MemberName,
			&i.Runtime,
			&i.Status,
			&i.Error,
			&i.FilesChanged,
			&i.SkillsUsed,
			&i.StartedAt,
			&i.EndedAt,
			&i.ProjectID,
			&i.ProjectName,
			&i.Reviewed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPersonMessage = `-- name: NextPersonMessage :one
SELECT id, seq, room_id, thread_id, sender_kind, user_id, member_id, body, mentions, created_at, turn_id FROM messages
WHERE thread_id = $1 AND sender_kind = 'user' AND created_at > $2
ORDER BY seq
LIMIT 1
`

type NextPersonMessageParams struct {
	ThreadID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

// The first thing a person said in a topic after a moment: after an
// agent's turn, where their verdict on it usually is.
func (q *Queries) NextPersonMessage(ctx context.Context, arg NextPersonMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, nextPersonMessage, arg.ThreadID, arg.CreatedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.RoomID,
		&i.ThreadID,
		&i.SenderKind,
		&i.UserID,
		&i.MemberID,
		&i.Body,
		&i.Mentions,
		&i.CreatedAt,
		&i.TurnID,
	)
	return i, err
}

const recordWikiReviews = `-- name: RecordWikiReviews :exec
INSERT INTO wiki_reviews (project_id, turn_id, upkeep_turn_id)
SELECT $1, t.id, $2 FROM turns t WHERE t.id = ANY ($3::uuid[])
ON CONFLICT DO NOTHING
`

type RecordWikiReviewsParams struct {
	ProjectID    pgtype.UUID
	UpkeepTurnID pgtype.UUID
	TurnIds      []pgtype.UUID
}

// Marks turns as gone over by a project's maintainer, in the turn that did
// it; a turn gone over before keeps its first record, and one that is gone
// by now is skipped.
func (q *Queries) RecordWikiReviews(ctx context.Context, arg RecordWikiReviewsParams) error {
	_, err := q.db.Exec(ctx, recordWikiReviews, arg.ProjectID, arg.UpkeepTurnID, arg.TurnIds)
	return err
}

const setProjectWikiSeen = `-- name: SetProjectWikiSeen :exec
UPDATE projects SET wiki_seen_seq = greatest(wiki_seen_seq, $1::bigint) WHERE id = $2
`

type SetProjectWikiSeenParams struct {
	Seq int64
	ID  pgtype.UUID
}

// Moves how far a project's maintainer has gone over its chat; forward only.
func (q *Queries) SetProjectWikiSeen(ctx context.Context, arg SetProjectWikiSeenParams) error {
	_, err := q.db.Exec(ctx, setProjectWikiSeen, arg.Seq, arg.ID)
	return err
}
