// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO workers (name, engines)
VALUES ($1, $2)
RETURNING id, name, engines, connected_at, last_seen_at, disconnected_at
`

type CreateWorkerParams struct {
	Name    string
	Engines []byte
}

// Registers a worker the hub has not seen before.
func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, createWorker, arg.Name, arg.Engines)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engines,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT id, name, engines, connected_at, last_seen_at, disconnected_at FROM workers WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id pgtype.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engines,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, engines, connected_at, last_seen_at, disconnected_at FROM workers ORDER BY name, connected_at
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Engines,
			&i.ConnectedAt,
			&i.LastSeenAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkerDisconnected = `-- name: MarkWorkerDisconnected :exec
UPDATE workers SET disconnected_at = now() WHERE id = $1
`

func (q *Queries) MarkWorkerDisconnected(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWorkerDisconnected, id)
	return err
}

const reconnectWorker = `-- name: ReconnectWorker :one
UPDATE workers SET
    name            = $2,
    engines         = $3,
    connected_at    = now(),
    last_seen_at    = now(),
    disconnected_at = NULL
WHERE id = $1
RETURNING id, name, engines, connected_at, last_seen_at, disconnected_at
`

type ReconnectWorkerParams struct {
	ID      pgtype.UUID
	Name    string
	Engines []byte
}

// Re-registers a known worker: refreshes its label and engines and resets
// the connection timestamps. Yields no row when the id is unknown.
func (q *Queries) ReconnectWorker(ctx context.Context, arg ReconnectWorkerParams) (Worker, error) {
	row := q.db.QueryRow(ctx, reconnectWorker, arg.ID, arg.Name, arg.Engines)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Engines,
		&i.ConnectedAt,
		&i.LastSeenAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const touchWorker = `-- name: TouchWorker :exec
UPDATE workers SET last_seen_at = now() WHERE id = $1
`

// Records that the worker was heard from.
func (q *Queries) TouchWorker(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchWorker, id)
	return err
}

const updateWorkerEngines = `-- name: UpdateWorkerEngines :exec
UPDATE workers SET engines = $2, last_seen_at = now() WHERE id = $1
`

type UpdateWorkerEnginesParams struct {
	ID      pgtype.UUID
	Engines []byte
}

func (q *Queries) UpdateWorkerEngines(ctx context.Context, arg UpdateWorkerEnginesParams) error {
	_, err := q.db.Exec(ctx, updateWorkerEngines, arg.ID, arg.Engines)
	return err
}
