// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listChainTurns = `-- name: ListChainTurns :many
SELECT t.id, t.member_id, t.room_id, t.thread_id, t.trigger_message_id, t.machine_id, t.session_id, t.runtime, t.kind, t.status, t.error, t.reply_message_id, t.transcript_path, t.input_tokens, t.cache_read_tokens, t.cache_write_tokens, t.output_tokens, t.files_changed, t.skills_used, t.wiki_pages, t.chain_message_id, t.woken_by_turn_id, t.worked, t.trusted_by, t.trusted_at, t.started_at, t.ended_at, th.number AS thread_number,
       coalesce(tm.body, '')::text AS trigger_body,
       coalesce(tm.title, '')::text AS trigger_title,
       coalesce(tm.sender_kind, '')::text AS trigger_kind
FROM turns t
JOIN threads th ON th.id = t.thread_id
LEFT JOIN messages tm ON tm.id = t.trigger_message_id
WHERE t.chain_message_id = $1
ORDER BY t.started_at
`

type ListChainTurnsRow struct {
	Turn         Turn
	ThreadNumber int32
	TriggerBody  string
	TriggerTitle string
	TriggerKind  string
}

// A piece of work's turns, oldest first, with their topics' numbers and
// the messages that set them off.
func (q *Queries) ListChainTurns(ctx context.Context, chainMessageID pgtype.UUID) ([]ListChainTurnsRow, error) {
	rows, err := q.db.Query(ctx, listChainTurns, chainMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChainTurnsRow
	for rows.Next() {
		var i ListChainTurnsRow
		if err := rows.Scan(
			&i.Turn.ID,
			&i.Turn.MemberID,
			&i.Turn.RoomID,
			&i.Turn.ThreadID,
			&i.Turn.TriggerMessageID,
			&i.Turn.MachineID,
			&i.Turn.SessionID,
			&i.Turn.Runtime,
			&i.Turn.Kind,
			&i.Turn.Status,
			&i.Turn.Error,
			&i.Turn.ReplyMessageID,
			&i.Turn.TranscriptPath,
			&i.Turn.InputTokens,
			&i.Turn.CacheReadTokens,
			&i.Turn.CacheWriteTokens,
			&i.Turn.OutputTokens,
			&i.Turn.FilesChanged,
			&i.Turn.SkillsUsed,
			&i.Turn.WikiPages,
			&i.Turn.ChainMessageID,
			&i.Turn.WokenByTurnID,
			&i.Turn.Worked,
			&i.Turn.TrustedBy,
			&i.Turn.TrustedAt,
			&i.Turn.StartedAt,
			&i.Turn.EndedAt,
			&i.ThreadNumber,
			&i.TriggerBody,
			&i.TriggerTitle,
			&i.TriggerKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChainWaits = `-- name: ListChainWaits :many
SELECT ap.turn_id, ap.created_at, ap.decided_at, ap.status
FROM approvals ap
JOIN turns t ON t.id = ap.turn_id
WHERE t.chain_message_id = $1 AND ap.reviewer = ''
ORDER BY ap.created_at
`

type ListChainWaitsRow struct {
	TurnID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	DecidedAt pgtype.Timestamptz
	Status    string
}

// How long a piece of work's turns waited for a person: the requests
// people were asked, when each was raised and settled.
func (q *Queries) ListChainWaits(ctx context.Context, chainMessageID pgtype.UUID) ([]ListChainWaitsRow, error) {
	rows, err := q.db.Query(ctx, listChainWaits, chainMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChainWaitsRow
	for rows.Next() {
		var i ListChainWaitsRow
		if err := rows.Scan(
			&i.TurnID,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomBranchEvents = `-- name: ListRoomBranchEvents :many
SELECT be.id, be.member_id, be.kind, be.commit_sha, be.ref, be.via_member_id, be.created_at FROM branch_events be
JOIN members m ON m.id = be.member_id
WHERE m.room_id = $1 AND be.created_at >= $2
ORDER BY be.created_at
`

type ListRoomBranchEventsParams struct {
	RoomID pgtype.UUID
	Since  pgtype.Timestamptz
}

// What became of the branches of a room's members since a moment, oldest
// first.
func (q *Queries) ListRoomBranchEvents(ctx context.Context, arg ListRoomBranchEventsParams) ([]BranchEvent, error) {
	rows, err := q.db.Query(ctx, listRoomBranchEvents, arg.RoomID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BranchEvent
	for rows.Next() {
		var i BranchEvent
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Kind,
			&i.CommitSha,
			&i.Ref,
			&i.ViaMemberID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomTaskTurns = `-- name: ListRoomTaskTurns :many
WITH chains AS (
    SELECT ct.chain_message_id, min(ct.started_at) AS began
    FROM turns ct
    WHERE ct.room_id = $1 AND ct.kind = 'chat' AND ct.chain_message_id IS NOT NULL
    GROUP BY ct.chain_message_id
    ORDER BY began DESC
    LIMIT $2
)
SELECT t.id, t.member_id, t.room_id, t.thread_id, t.trigger_message_id, t.machine_id, t.session_id, t.runtime, t.kind, t.status, t.error, t.reply_message_id, t.transcript_path, t.input_tokens, t.cache_read_tokens, t.cache_write_tokens, t.output_tokens, t.files_changed, t.skills_used, t.wiki_pages, t.chain_message_id, t.woken_by_turn_id, t.worked, t.trusted_by, t.trusted_at, t.started_at, t.ended_at, th.number AS thread_number,
       coalesce(tm.body, '')::text AS trigger_body,
       coalesce(tm.title, '')::text AS trigger_title,
       coalesce(tm.sender_kind, '')::text AS trigger_kind,
       EXISTS (SELECT 1 FROM approvals ap WHERE ap.turn_id = t.id AND ap.status = 'pending')::boolean AS waiting
FROM turns t
JOIN chains c ON c.chain_message_id = t.chain_message_id
JOIN threads th ON th.id = t.thread_id
LEFT JOIN messages tm ON tm.id = t.trigger_message_id
WHERE t.kind = 'chat'
ORDER BY t.started_at
`

type ListRoomTaskTurnsParams struct {
	RoomID pgtype.UUID
	Chains int32
}

type ListRoomTaskTurnsRow struct {
	Turn         Turn
	ThreadNumber int32
	TriggerBody  string
	TriggerTitle string
	TriggerKind  string
	Waiting      bool
}

// The chat turns of a room's latest pieces of work, oldest first, with what
// the task board needs of each: its topic's number, the message that set
// it off (its words, what a member handing it on called it, who wrote it)
// and whether a request of it waits for a person.
func (q *Queries) ListRoomTaskTurns(ctx context.Context, arg ListRoomTaskTurnsParams) ([]ListRoomTaskTurnsRow, error) {
	rows, err := q.db.Query(ctx, listRoomTaskTurns, arg.RoomID, arg.Chains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomTaskTurnsRow
	for rows.Next() {
		var i ListRoomTaskTurnsRow
		if err := rows.Scan(
			&i.Turn.ID,
			&i.Turn.MemberID,
			&i.Turn.RoomID,
			&i.Turn.ThreadID,
			&i.Turn.TriggerMessageID,
			&i.Turn.MachineID,
			&i.Turn.SessionID,
			&i.Turn.Runtime,
			&i.Turn.Kind,
			&i.Turn.Status,
			&i.Turn.Error,
			&i.Turn.ReplyMessageID,
			&i.Turn.TranscriptPath,
			&i.Turn.InputTokens,
			&i.Turn.CacheReadTokens,
			&i.Turn.CacheWriteTokens,
			&i.Turn.OutputTokens,
			&i.Turn.FilesChanged,
			&i.Turn.SkillsUsed,
			&i.Turn.WikiPages,
			&i.Turn.ChainMessageID,
			&i.Turn.WokenByTurnID,
			&i.Turn.Worked,
			&i.Turn.TrustedBy,
			&i.Turn.TrustedAt,
			&i.Turn.StartedAt,
			&i.Turn.EndedAt,
			&i.ThreadNumber,
			&i.TriggerBody,
			&i.TriggerTitle,
			&i.TriggerKind,
			&i.Waiting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageTurns = `-- name: ListUsageTurns :many
SELECT t.id, t.member_id, t.room_id, t.thread_id, th.number AS thread_number, t.runtime, t.kind, t.status,
       t.chain_message_id, t.started_at, t.ended_at,
       t.input_tokens, t.cache_read_tokens, t.cache_write_tokens, t.output_tokens,
       mb.display_name AS member_name, mb.agent_id, coalesce(nullif(mb.model, ''), ag.model, '')::text AS model,
       r.project_id, p.name AS project_name, coalesce(cm.body, '')::text AS chain_body
FROM turns t
JOIN threads th ON th.id = t.thread_id
JOIN members mb ON mb.id = t.member_id
LEFT JOIN agents ag ON ag.id = mb.agent_id
JOIN rooms r ON r.id = t.room_id
JOIN projects p ON p.id = r.project_id
LEFT JOIN messages cm ON cm.id = t.chain_message_id
WHERE t.started_at >= $1
  AND ($2::uuid IS NULL OR r.project_id = $2::uuid)
ORDER BY t.started_at
`

type ListUsageTurnsParams struct {
	Since     pgtype.Timestamptz
	ProjectID pgtype.UUID
}

type ListUsageTurnsRow struct {
	ID               pgtype.UUID
	MemberID         pgtype.UUID
	RoomID           pgtype.UUID
	ThreadID         pgtype.UUID
	ThreadNumber     int32
	Runtime          string
	Kind             string
	Status           string
	ChainMessageID   pgtype.UUID
	StartedAt        pgtype.Timestamptz
	EndedAt          pgtype.Timestamptz
	InputTokens      int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	OutputTokens     int64
	MemberName       string
	AgentID          pgtype.UUID
	Model            string
	ProjectID        pgtype.UUID
	ProjectName      string
	ChainBody        string
}

// The turns begun since a moment, of one project or every one, with what
// the usage page sums them by: who ran them on what, in which topic, as
// part of which piece of work.
func (q *Queries) ListUsageTurns(ctx context.Context, arg ListUsageTurnsParams) ([]ListUsageTurnsRow, error) {
	rows, err := q.db.Query(ctx, listUsageTurns, arg.Since, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageTurnsRow
	for rows.Next() {
		var i ListUsageTurnsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.RoomID,
			&i.ThreadID,
			&i.ThreadNumber,
			&i.Runtime,
			&i.Kind,
			&i.Status,
			&i.ChainMessageID,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.OutputTokens,
			&i.MemberName,
			&i.AgentID,
			&i.Model,
			&i.ProjectID,
			&i.ProjectName,
			&i.ChainBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBranchEvent = `-- name: RecordBranchEvent :one

INSERT INTO branch_events (member_id, kind, commit_sha, ref, via_member_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, member_id, kind, commit_sha, ref, via_member_id, created_at
`

type RecordBranchEventParams struct {
	MemberID    pgtype.UUID
	Kind        string
	CommitSha   string
	Ref         string
	ViaMemberID pgtype.UUID
}

// What the task board, a piece of work's page and the usage page read
// (docs/webui.md 4.20).
// What became of a member's branch: merged onto the main line, or reset
// to it with its work archived.
func (q *Queries) RecordBranchEvent(ctx context.Context, arg RecordBranchEventParams) (BranchEvent, error) {
	row := q.db.QueryRow(ctx, recordBranchEvent,
		arg.MemberID,
		arg.Kind,
		arg.CommitSha,
		arg.Ref,
		arg.ViaMemberID,
	)
	var i BranchEvent
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Kind,
		&i.CommitSha,
		&i.Ref,
		&i.ViaMemberID,
		&i.CreatedAt,
	)
	return i, err
}
